# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hiwonder_interfaces/Led.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Led(genpy.Message):
  _md5sum = "9d75341b887ccec081eae7150fd4708f"
  _type = "hiwonder_interfaces/Led"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8  brightness     # LED灯亮度
uint16 on_ticks       # LED亮起的时长 毫秒
uint16 off_ticks      # LED熄灭的时长 毫秒
uint16 repeat         # LED灯闪烁的重复次数
"""
  __slots__ = ['brightness','on_ticks','off_ticks','repeat']
  _slot_types = ['uint8','uint16','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       brightness,on_ticks,off_ticks,repeat

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Led, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.brightness is None:
        self.brightness = 0
      if self.on_ticks is None:
        self.on_ticks = 0
      if self.off_ticks is None:
        self.off_ticks = 0
      if self.repeat is None:
        self.repeat = 0
    else:
      self.brightness = 0
      self.on_ticks = 0
      self.off_ticks = 0
      self.repeat = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B3H().pack(_x.brightness, _x.on_ticks, _x.off_ticks, _x.repeat))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.brightness, _x.on_ticks, _x.off_ticks, _x.repeat,) = _get_struct_B3H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B3H().pack(_x.brightness, _x.on_ticks, _x.off_ticks, _x.repeat))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.brightness, _x.on_ticks, _x.off_ticks, _x.repeat,) = _get_struct_B3H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B3H = None
def _get_struct_B3H():
    global _struct_B3H
    if _struct_B3H is None:
        _struct_B3H = struct.Struct("<B3H")
    return _struct_B3H
