# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hiwonder_interfaces/ObjectsInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import hiwonder_interfaces.msg

class ObjectsInfo(genpy.Message):
  _md5sum = "44a9b7876b169d055c96381fead947aa"
  _type = "hiwonder_interfaces/ObjectsInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """ hiwonder_interfaces/ObjectInfo[] data

================================================================================
MSG: hiwonder_interfaces/ObjectInfo
# 颜色标签，如'red1', 'green2', 'blue3', 'BananaPeel', 'BrokenBones'
string label

# 物体的像素中心点坐标
hiwonder_interfaces/PixelPosition center

# 物体的旋转角度，旋转角度指水平轴（x轴）逆时针旋转，与碰到的矩形的第一条边的夹角
int16 yaw

# 物体图像尺寸
hiwonder_interfaces/ImageSize size

# 物体高度 
float64 height

================================================================================
MSG: hiwonder_interfaces/PixelPosition
uint16 x
uint16 y

================================================================================
MSG: hiwonder_interfaces/ImageSize
uint16 width
uint16 height"""
  __slots__ = ['data']
  _slot_types = ['hiwonder_interfaces/ObjectInfo[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObjectsInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.data is None:
        self.data = []
    else:
      self.data = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.data)
      buff.write(_struct_I.pack(length))
      for val1 in self.data:
        _x = val1.label
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v1 = val1.center
        _x = _v1
        buff.write(_get_struct_2H().pack(_x.x, _x.y))
        _x = val1.yaw
        buff.write(_get_struct_h().pack(_x))
        _v2 = val1.size
        _x = _v2
        buff.write(_get_struct_2H().pack(_x.width, _x.height))
        _x = val1.height
        buff.write(_get_struct_d().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.data is None:
        self.data = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.data = []
      for i in range(0, length):
        val1 = hiwonder_interfaces.msg.ObjectInfo()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.label = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.label = str[start:end]
        _v3 = val1.center
        _x = _v3
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2H().unpack(str[start:end])
        start = end
        end += 2
        (val1.yaw,) = _get_struct_h().unpack(str[start:end])
        _v4 = val1.size
        _x = _v4
        start = end
        end += 4
        (_x.width, _x.height,) = _get_struct_2H().unpack(str[start:end])
        start = end
        end += 8
        (val1.height,) = _get_struct_d().unpack(str[start:end])
        self.data.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.data)
      buff.write(_struct_I.pack(length))
      for val1 in self.data:
        _x = val1.label
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v5 = val1.center
        _x = _v5
        buff.write(_get_struct_2H().pack(_x.x, _x.y))
        _x = val1.yaw
        buff.write(_get_struct_h().pack(_x))
        _v6 = val1.size
        _x = _v6
        buff.write(_get_struct_2H().pack(_x.width, _x.height))
        _x = val1.height
        buff.write(_get_struct_d().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.data is None:
        self.data = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.data = []
      for i in range(0, length):
        val1 = hiwonder_interfaces.msg.ObjectInfo()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.label = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.label = str[start:end]
        _v7 = val1.center
        _x = _v7
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2H().unpack(str[start:end])
        start = end
        end += 2
        (val1.yaw,) = _get_struct_h().unpack(str[start:end])
        _v8 = val1.size
        _x = _v8
        start = end
        end += 4
        (_x.width, _x.height,) = _get_struct_2H().unpack(str[start:end])
        start = end
        end += 8
        (val1.height,) = _get_struct_d().unpack(str[start:end])
        self.data.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2H = None
def _get_struct_2H():
    global _struct_2H
    if _struct_2H is None:
        _struct_2H = struct.Struct("<2H")
    return _struct_2H
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
_struct_h = None
def _get_struct_h():
    global _struct_h
    if _struct_h is None:
        _struct_h = struct.Struct("<h")
    return _struct_h
