// Auto-generated. Do not edit!

// (in-package hiwonder_interfaces.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let Grasp = require('./Grasp.js');

//-----------------------------------------------------------

class MoveGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.grasp = null;
    }
    else {
      if (initObj.hasOwnProperty('grasp')) {
        this.grasp = initObj.grasp
      }
      else {
        this.grasp = new Grasp();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MoveGoal
    // Serialize message field [grasp]
    bufferOffset = Grasp.serialize(obj.grasp, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MoveGoal
    let len;
    let data = new MoveGoal(null);
    // Deserialize message field [grasp]
    data.grasp = Grasp.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += Grasp.getMessageSize(object.grasp);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'hiwonder_interfaces/MoveGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '4e8dc9d50c716c29037a12241ed7c244';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    hiwonder_interfaces/Grasp grasp
    
    ================================================================================
    MSG: hiwonder_interfaces/Grasp
    # pick, place
    string mode
    
    # 夹取时的姿态和位置
    geometry_msgs/Point position
    
    float64 pitch
    float64 align_angle
    
    # 接近时的距离和方向
    geometry_msgs/Vector3 grasp_approach
    
    # 撤离时的距离和方向
    geometry_msgs/Vector3 grasp_retreat
    
    # 夹取时夹持器姿态
    uint16 grasp_posture
    
    # 夹取前夹持器姿态
    uint16 pre_grasp_posture
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Vector3
    # This represents a vector in free space. 
    # It is only meant to represent a direction. Therefore, it does not
    # make sense to apply a translation to it (e.g., when applying a 
    # generic rigid transformation to a Vector3, tf2 will only apply the
    # rotation). If you want your data to be translatable too, use the
    # geometry_msgs/Point message instead.
    
    float64 x
    float64 y
    float64 z
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MoveGoal(null);
    if (msg.grasp !== undefined) {
      resolved.grasp = Grasp.Resolve(msg.grasp)
    }
    else {
      resolved.grasp = new Grasp()
    }

    return resolved;
    }
};

module.exports = MoveGoal;
