# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hiwonder_interfaces/Grasp.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Grasp(genpy.Message):
  _md5sum = "1e4e2be316d6a67c5705e66022e5a73c"
  _type = "hiwonder_interfaces/Grasp"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# pick, place
string mode

# 夹取时的姿态和位置
geometry_msgs/Point position

float64 pitch
float64 align_angle

# 接近时的距离和方向
geometry_msgs/Vector3 grasp_approach

# 撤离时的距离和方向
geometry_msgs/Vector3 grasp_retreat

# 夹取时夹持器姿态
uint16 grasp_posture

# 夹取前夹持器姿态
uint16 pre_grasp_posture

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['mode','position','pitch','align_angle','grasp_approach','grasp_retreat','grasp_posture','pre_grasp_posture']
  _slot_types = ['string','geometry_msgs/Point','float64','float64','geometry_msgs/Vector3','geometry_msgs/Vector3','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mode,position,pitch,align_angle,grasp_approach,grasp_retreat,grasp_posture,pre_grasp_posture

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Grasp, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.mode is None:
        self.mode = ''
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.pitch is None:
        self.pitch = 0.
      if self.align_angle is None:
        self.align_angle = 0.
      if self.grasp_approach is None:
        self.grasp_approach = geometry_msgs.msg.Vector3()
      if self.grasp_retreat is None:
        self.grasp_retreat = geometry_msgs.msg.Vector3()
      if self.grasp_posture is None:
        self.grasp_posture = 0
      if self.pre_grasp_posture is None:
        self.pre_grasp_posture = 0
    else:
      self.mode = ''
      self.position = geometry_msgs.msg.Point()
      self.pitch = 0.
      self.align_angle = 0.
      self.grasp_approach = geometry_msgs.msg.Vector3()
      self.grasp_retreat = geometry_msgs.msg.Vector3()
      self.grasp_posture = 0
      self.pre_grasp_posture = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_11d2H().pack(_x.position.x, _x.position.y, _x.position.z, _x.pitch, _x.align_angle, _x.grasp_approach.x, _x.grasp_approach.y, _x.grasp_approach.z, _x.grasp_retreat.x, _x.grasp_retreat.y, _x.grasp_retreat.z, _x.grasp_posture, _x.pre_grasp_posture))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.grasp_approach is None:
        self.grasp_approach = geometry_msgs.msg.Vector3()
      if self.grasp_retreat is None:
        self.grasp_retreat = geometry_msgs.msg.Vector3()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.mode = str[start:end]
      _x = self
      start = end
      end += 92
      (_x.position.x, _x.position.y, _x.position.z, _x.pitch, _x.align_angle, _x.grasp_approach.x, _x.grasp_approach.y, _x.grasp_approach.z, _x.grasp_retreat.x, _x.grasp_retreat.y, _x.grasp_retreat.z, _x.grasp_posture, _x.pre_grasp_posture,) = _get_struct_11d2H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_11d2H().pack(_x.position.x, _x.position.y, _x.position.z, _x.pitch, _x.align_angle, _x.grasp_approach.x, _x.grasp_approach.y, _x.grasp_approach.z, _x.grasp_retreat.x, _x.grasp_retreat.y, _x.grasp_retreat.z, _x.grasp_posture, _x.pre_grasp_posture))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.grasp_approach is None:
        self.grasp_approach = geometry_msgs.msg.Vector3()
      if self.grasp_retreat is None:
        self.grasp_retreat = geometry_msgs.msg.Vector3()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.mode = str[start:end]
      _x = self
      start = end
      end += 92
      (_x.position.x, _x.position.y, _x.position.z, _x.pitch, _x.align_angle, _x.grasp_approach.x, _x.grasp_approach.y, _x.grasp_approach.z, _x.grasp_retreat.x, _x.grasp_retreat.y, _x.grasp_retreat.z, _x.grasp_posture, _x.pre_grasp_posture,) = _get_struct_11d2H().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_11d2H = None
def _get_struct_11d2H():
    global _struct_11d2H
    if _struct_11d2H is None:
        _struct_11d2H = struct.Struct("<11d2H")
    return _struct_11d2H
