# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hiwonder_interfaces/MoveResult.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import hiwonder_interfaces.msg

class MoveResult(genpy.Message):
  _md5sum = "ee1ee077361bf11d478f1e601fee6a92"
  _type = "hiwonder_interfaces/MoveResult"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
hiwonder_interfaces/GraspState result

================================================================================
MSG: hiwonder_interfaces/GraspState
bool complete
hiwonder_interfaces/EulerAngles grasp_posture

================================================================================
MSG: hiwonder_interfaces/EulerAngles
float64 r
float64 p
float64 y
"""
  __slots__ = ['result']
  _slot_types = ['hiwonder_interfaces/GraspState']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       result

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MoveResult, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.result is None:
        self.result = hiwonder_interfaces.msg.GraspState()
    else:
      self.result = hiwonder_interfaces.msg.GraspState()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B3d().pack(_x.result.complete, _x.result.grasp_posture.r, _x.result.grasp_posture.p, _x.result.grasp_posture.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.result is None:
        self.result = hiwonder_interfaces.msg.GraspState()
      end = 0
      _x = self
      start = end
      end += 25
      (_x.result.complete, _x.result.grasp_posture.r, _x.result.grasp_posture.p, _x.result.grasp_posture.y,) = _get_struct_B3d().unpack(str[start:end])
      self.result.complete = bool(self.result.complete)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B3d().pack(_x.result.complete, _x.result.grasp_posture.r, _x.result.grasp_posture.p, _x.result.grasp_posture.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.result is None:
        self.result = hiwonder_interfaces.msg.GraspState()
      end = 0
      _x = self
      start = end
      end += 25
      (_x.result.complete, _x.result.grasp_posture.r, _x.result.grasp_posture.p, _x.result.grasp_posture.y,) = _get_struct_B3d().unpack(str[start:end])
      self.result.complete = bool(self.result.complete)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B3d = None
def _get_struct_B3d():
    global _struct_B3d
    if _struct_B3d is None:
        _struct_B3d = struct.Struct("<B3d")
    return _struct_B3d
