# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hiwonder_interfaces/ObjectPose.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import hiwonder_interfaces.msg

class ObjectPose(genpy.Message):
  _md5sum = "38c75b0b27ce3ab74cbda554632b2fd4"
  _type = "hiwonder_interfaces/ObjectPose"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# 颜色标签，如'red1', 'green2', 'blue3'
# 垃圾标签, 如'BananaPeel'
string label

# 物体的物理世界中心点坐标
float64 x
float64 y

# 机械臂夹持器转到和物体平行的角度
int16 yaw

# 碰撞区域
hiwonder_interfaces/PixelPosition[] collision_roi

# 表示夹取的物体是否与周围的物体足够近，导致夹持器夹取时会产生碰撞
# 如果为真，则yaw不可用
bool collision

================================================================================
MSG: hiwonder_interfaces/PixelPosition
uint16 x
uint16 y
"""
  __slots__ = ['label','x','y','yaw','collision_roi','collision']
  _slot_types = ['string','float64','float64','int16','hiwonder_interfaces/PixelPosition[]','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       label,x,y,yaw,collision_roi,collision

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObjectPose, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.label is None:
        self.label = ''
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.yaw is None:
        self.yaw = 0
      if self.collision_roi is None:
        self.collision_roi = []
      if self.collision is None:
        self.collision = False
    else:
      self.label = ''
      self.x = 0.
      self.y = 0.
      self.yaw = 0
      self.collision_roi = []
      self.collision = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2dh().pack(_x.x, _x.y, _x.yaw))
      length = len(self.collision_roi)
      buff.write(_struct_I.pack(length))
      for val1 in self.collision_roi:
        _x = val1
        buff.write(_get_struct_2H().pack(_x.x, _x.y))
      _x = self.collision
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.collision_roi is None:
        self.collision_roi = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label = str[start:end]
      _x = self
      start = end
      end += 18
      (_x.x, _x.y, _x.yaw,) = _get_struct_2dh().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.collision_roi = []
      for i in range(0, length):
        val1 = hiwonder_interfaces.msg.PixelPosition()
        _x = val1
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2H().unpack(str[start:end])
        self.collision_roi.append(val1)
      start = end
      end += 1
      (self.collision,) = _get_struct_B().unpack(str[start:end])
      self.collision = bool(self.collision)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.label
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2dh().pack(_x.x, _x.y, _x.yaw))
      length = len(self.collision_roi)
      buff.write(_struct_I.pack(length))
      for val1 in self.collision_roi:
        _x = val1
        buff.write(_get_struct_2H().pack(_x.x, _x.y))
      _x = self.collision
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.collision_roi is None:
        self.collision_roi = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.label = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.label = str[start:end]
      _x = self
      start = end
      end += 18
      (_x.x, _x.y, _x.yaw,) = _get_struct_2dh().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.collision_roi = []
      for i in range(0, length):
        val1 = hiwonder_interfaces.msg.PixelPosition()
        _x = val1
        start = end
        end += 4
        (_x.x, _x.y,) = _get_struct_2H().unpack(str[start:end])
        self.collision_roi.append(val1)
      start = end
      end += 1
      (self.collision,) = _get_struct_B().unpack(str[start:end])
      self.collision = bool(self.collision)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2H = None
def _get_struct_2H():
    global _struct_2H
    if _struct_2H is None:
        _struct_2H = struct.Struct("<2H")
    return _struct_2H
_struct_2dh = None
def _get_struct_2dh():
    global _struct_2dh
    if _struct_2dh is None:
        _struct_2dh = struct.Struct("<2dh")
    return _struct_2dh
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
