// Auto-generated. Do not edit!

// (in-package hiwonder_interfaces.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let GraspState = require('./GraspState.js');

//-----------------------------------------------------------

class MoveResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.result = null;
    }
    else {
      if (initObj.hasOwnProperty('result')) {
        this.result = initObj.result
      }
      else {
        this.result = new GraspState();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MoveResult
    // Serialize message field [result]
    bufferOffset = GraspState.serialize(obj.result, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MoveResult
    let len;
    let data = new MoveResult(null);
    // Deserialize message field [result]
    data.result = GraspState.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 25;
  }

  static datatype() {
    // Returns string type for a message object
    return 'hiwonder_interfaces/MoveResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'ee1ee077361bf11d478f1e601fee6a92';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    hiwonder_interfaces/GraspState result
    
    ================================================================================
    MSG: hiwonder_interfaces/GraspState
    bool complete
    hiwonder_interfaces/EulerAngles grasp_posture
    
    ================================================================================
    MSG: hiwonder_interfaces/EulerAngles
    float64 r
    float64 p
    float64 y
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MoveResult(null);
    if (msg.result !== undefined) {
      resolved.result = GraspState.Resolve(msg.result)
    }
    else {
      resolved.result = new GraspState()
    }

    return resolved;
    }
};

module.exports = MoveResult;
