(cl:defpackage xf_mic_asr_offline-srv
  (:use )
  (:export
   "GETOFFLINERESULT"
   "<GETOFFLINERESULT-REQUEST>"
   "GETOFFLINERESULT-REQUEST"
   "<GETOFFLINERESULT-RESPONSE>"
   "GETOFFLINERESULT-RESPONSE"
   "SETSTRING"
   "<SETSTRING-REQUEST>"
   "SETSTRING-REQUEST"
   "<SETSTRING-RESPONSE>"
   "SETSTRING-RESPONSE"
  ))

