// Generated by gencpp from file hiwonder_interfaces/Buzzer.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_BUZZER_H
#define HIWONDER_INTERFACES_MESSAGE_BUZZER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct Buzzer_
{
  typedef Buzzer_<ContainerAllocator> Type;

  Buzzer_()
    : freq(0)
    , on_ticks(0)
    , off_ticks(0)
    , repeat(0)  {
    }
  Buzzer_(const ContainerAllocator& _alloc)
    : freq(0)
    , on_ticks(0)
    , off_ticks(0)
    , repeat(0)  {
  (void)_alloc;
    }



   typedef uint16_t _freq_type;
  _freq_type freq;

   typedef uint16_t _on_ticks_type;
  _on_ticks_type on_ticks;

   typedef uint16_t _off_ticks_type;
  _off_ticks_type off_ticks;

   typedef uint16_t _repeat_type;
  _repeat_type repeat;





  typedef boost::shared_ptr< ::hiwonder_interfaces::Buzzer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::Buzzer_<ContainerAllocator> const> ConstPtr;

}; // struct Buzzer_

typedef ::hiwonder_interfaces::Buzzer_<std::allocator<void> > Buzzer;

typedef boost::shared_ptr< ::hiwonder_interfaces::Buzzer > BuzzerPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::Buzzer const> BuzzerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::Buzzer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::Buzzer_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::Buzzer_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::Buzzer_<ContainerAllocator2> & rhs)
{
  return lhs.freq == rhs.freq &&
    lhs.on_ticks == rhs.on_ticks &&
    lhs.off_ticks == rhs.off_ticks &&
    lhs.repeat == rhs.repeat;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::Buzzer_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::Buzzer_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::Buzzer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::Buzzer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::Buzzer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::Buzzer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::Buzzer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::Buzzer_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::Buzzer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c553d26ba33d63f49b15ae65585246e6";
  }

  static const char* value(const ::hiwonder_interfaces::Buzzer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc553d26ba33d63f4ULL;
  static const uint64_t static_value2 = 0x9b15ae65585246e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::Buzzer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/Buzzer";
  }

  static const char* value(const ::hiwonder_interfaces::Buzzer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::Buzzer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 freq           # 蜂鸣器声音频率\n"
"uint16 on_ticks       # 蜂鸣器响的时长 毫秒\n"
"uint16 off_ticks      # 蜂鸣器不响的时长 毫秒\n"
"uint16 repeat         # 蜂鸣器响与不响重复次数\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::Buzzer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::Buzzer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.freq);
      stream.next(m.on_ticks);
      stream.next(m.off_ticks);
      stream.next(m.repeat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Buzzer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::Buzzer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::Buzzer_<ContainerAllocator>& v)
  {
    s << indent << "freq: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.freq);
    s << indent << "on_ticks: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.on_ticks);
    s << indent << "off_ticks: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.off_ticks);
    s << indent << "repeat: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.repeat);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_BUZZER_H
