// Generated by gencpp from file hiwonder_interfaces/EulerAngles.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_EULERANGLES_H
#define HIWONDER_INTERFACES_MESSAGE_EULERANGLES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct EulerAngles_
{
  typedef EulerAngles_<ContainerAllocator> Type;

  EulerAngles_()
    : r(0.0)
    , p(0.0)
    , y(0.0)  {
    }
  EulerAngles_(const ContainerAllocator& _alloc)
    : r(0.0)
    , p(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef double _r_type;
  _r_type r;

   typedef double _p_type;
  _p_type p;

   typedef double _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::hiwonder_interfaces::EulerAngles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::EulerAngles_<ContainerAllocator> const> ConstPtr;

}; // struct EulerAngles_

typedef ::hiwonder_interfaces::EulerAngles_<std::allocator<void> > EulerAngles;

typedef boost::shared_ptr< ::hiwonder_interfaces::EulerAngles > EulerAnglesPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::EulerAngles const> EulerAnglesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::EulerAngles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::EulerAngles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::EulerAngles_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::EulerAngles_<ContainerAllocator2> & rhs)
{
  return lhs.r == rhs.r &&
    lhs.p == rhs.p &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::EulerAngles_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::EulerAngles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::EulerAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::EulerAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::EulerAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::EulerAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::EulerAngles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::EulerAngles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::EulerAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5585e6b09b13f56ed964334fed50470";
  }

  static const char* value(const ::hiwonder_interfaces::EulerAngles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5585e6b09b13f56ULL;
  static const uint64_t static_value2 = 0xed964334fed50470ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::EulerAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/EulerAngles";
  }

  static const char* value(const ::hiwonder_interfaces::EulerAngles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::EulerAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 r\n"
"float64 p\n"
"float64 y\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::EulerAngles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::EulerAngles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.r);
      stream.next(m.p);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EulerAngles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::EulerAngles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::EulerAngles_<ContainerAllocator>& v)
  {
    s << indent << "r: ";
    Printer<double>::stream(s, indent + "  ", v.r);
    s << indent << "p: ";
    Printer<double>::stream(s, indent + "  ", v.p);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_EULERANGLES_H
