// Generated by gencpp from file hiwonder_interfaces/GetLink.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_GETLINK_H
#define HIWONDER_INTERFACES_MESSAGE_GETLINK_H

#include <ros/service_traits.h>


#include <hiwonder_interfaces/GetLinkRequest.h>
#include <hiwonder_interfaces/GetLinkResponse.h>


namespace hiwonder_interfaces
{

struct GetLink
{

typedef GetLinkRequest Request;
typedef GetLinkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLink
} // namespace hiwonder_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hiwonder_interfaces::GetLink > {
  static const char* value()
  {
    return "f52e183781a78fdf83d51e914c2363e3";
  }

  static const char* value(const ::hiwonder_interfaces::GetLink&) { return value(); }
};

template<>
struct DataType< ::hiwonder_interfaces::GetLink > {
  static const char* value()
  {
    return "hiwonder_interfaces/GetLink";
  }

  static const char* value(const ::hiwonder_interfaces::GetLink&) { return value(); }
};


// service_traits::MD5Sum< ::hiwonder_interfaces::GetLinkRequest> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::GetLink >
template<>
struct MD5Sum< ::hiwonder_interfaces::GetLinkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::GetLink >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetLinkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::GetLinkRequest> should match
// service_traits::DataType< ::hiwonder_interfaces::GetLink >
template<>
struct DataType< ::hiwonder_interfaces::GetLinkRequest>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::GetLink >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetLinkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hiwonder_interfaces::GetLinkResponse> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::GetLink >
template<>
struct MD5Sum< ::hiwonder_interfaces::GetLinkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::GetLink >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetLinkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::GetLinkResponse> should match
// service_traits::DataType< ::hiwonder_interfaces::GetLink >
template<>
struct DataType< ::hiwonder_interfaces::GetLinkResponse>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::GetLink >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetLinkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_GETLINK_H
