// Generated by gencpp from file hiwonder_interfaces/GetLinkResponse.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_GETLINKRESPONSE_H
#define HIWONDER_INTERFACES_MESSAGE_GETLINKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct GetLinkResponse_
{
  typedef GetLinkResponse_<ContainerAllocator> Type;

  GetLinkResponse_()
    : success(false)
    , data()  {
    }
  GetLinkResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetLinkResponse_

typedef ::hiwonder_interfaces::GetLinkResponse_<std::allocator<void> > GetLinkResponse;

typedef boost::shared_ptr< ::hiwonder_interfaces::GetLinkResponse > GetLinkResponsePtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::GetLinkResponse const> GetLinkResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f52e183781a78fdf83d51e914c2363e3";
  }

  static const char* value(const ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf52e183781a78fdfULL;
  static const uint64_t static_value2 = 0x83d51e914c2363e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/GetLinkResponse";
  }

  static const char* value(const ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"float32[] data\n"
"\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetLinkResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::GetLinkResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_GETLINKRESPONSE_H
