// Generated by gencpp from file hiwonder_interfaces/GetRobotPose.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_GETROBOTPOSE_H
#define HIWONDER_INTERFACES_MESSAGE_GETROBOTPOSE_H

#include <ros/service_traits.h>


#include <hiwonder_interfaces/GetRobotPoseRequest.h>
#include <hiwonder_interfaces/GetRobotPoseResponse.h>


namespace hiwonder_interfaces
{

struct GetRobotPose
{

typedef GetRobotPoseRequest Request;
typedef GetRobotPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRobotPose
} // namespace hiwonder_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hiwonder_interfaces::GetRobotPose > {
  static const char* value()
  {
    return "7e34dc38014b735f72f1da76fa4f5008";
  }

  static const char* value(const ::hiwonder_interfaces::GetRobotPose&) { return value(); }
};

template<>
struct DataType< ::hiwonder_interfaces::GetRobotPose > {
  static const char* value()
  {
    return "hiwonder_interfaces/GetRobotPose";
  }

  static const char* value(const ::hiwonder_interfaces::GetRobotPose&) { return value(); }
};


// service_traits::MD5Sum< ::hiwonder_interfaces::GetRobotPoseRequest> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::GetRobotPose >
template<>
struct MD5Sum< ::hiwonder_interfaces::GetRobotPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::GetRobotPose >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetRobotPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::GetRobotPoseRequest> should match
// service_traits::DataType< ::hiwonder_interfaces::GetRobotPose >
template<>
struct DataType< ::hiwonder_interfaces::GetRobotPoseRequest>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::GetRobotPose >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetRobotPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hiwonder_interfaces::GetRobotPoseResponse> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::GetRobotPose >
template<>
struct MD5Sum< ::hiwonder_interfaces::GetRobotPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::GetRobotPose >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetRobotPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::GetRobotPoseResponse> should match
// service_traits::DataType< ::hiwonder_interfaces::GetRobotPose >
template<>
struct DataType< ::hiwonder_interfaces::GetRobotPoseResponse>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::GetRobotPose >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetRobotPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_GETROBOTPOSE_H
