// Generated by gencpp from file hiwonder_interfaces/GetRobotPoseResponse.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_GETROBOTPOSERESPONSE_H
#define HIWONDER_INTERFACES_MESSAGE_GETROBOTPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct GetRobotPoseResponse_
{
  typedef GetRobotPoseResponse_<ContainerAllocator> Type;

  GetRobotPoseResponse_()
    : success(false)
    , solution(false)
    , pose()  {
    }
  GetRobotPoseResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , solution(false)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _solution_type;
  _solution_type solution;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetRobotPoseResponse_

typedef ::hiwonder_interfaces::GetRobotPoseResponse_<std::allocator<void> > GetRobotPoseResponse;

typedef boost::shared_ptr< ::hiwonder_interfaces::GetRobotPoseResponse > GetRobotPoseResponsePtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::GetRobotPoseResponse const> GetRobotPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.solution == rhs.solution &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e34dc38014b735f72f1da76fa4f5008";
  }

  static const char* value(const ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e34dc38014b735fULL;
  static const uint64_t static_value2 = 0x72f1da76fa4f5008ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/GetRobotPoseResponse";
  }

  static const char* value(const ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"bool solution\n"
"geometry_msgs/Pose pose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.solution);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRobotPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::GetRobotPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "solution: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.solution);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_GETROBOTPOSERESPONSE_H
