// Generated by gencpp from file hiwonder_interfaces/GetTarget.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_GETTARGET_H
#define HIWONDER_INTERFACES_MESSAGE_GETTARGET_H

#include <ros/service_traits.h>


#include <hiwonder_interfaces/GetTargetRequest.h>
#include <hiwonder_interfaces/GetTargetResponse.h>


namespace hiwonder_interfaces
{

struct GetTarget
{

typedef GetTargetRequest Request;
typedef GetTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTarget
} // namespace hiwonder_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hiwonder_interfaces::GetTarget > {
  static const char* value()
  {
    return "a969347dbd0044352898c1217b7481aa";
  }

  static const char* value(const ::hiwonder_interfaces::GetTarget&) { return value(); }
};

template<>
struct DataType< ::hiwonder_interfaces::GetTarget > {
  static const char* value()
  {
    return "hiwonder_interfaces/GetTarget";
  }

  static const char* value(const ::hiwonder_interfaces::GetTarget&) { return value(); }
};


// service_traits::MD5Sum< ::hiwonder_interfaces::GetTargetRequest> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::GetTarget >
template<>
struct MD5Sum< ::hiwonder_interfaces::GetTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::GetTarget >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::GetTargetRequest> should match
// service_traits::DataType< ::hiwonder_interfaces::GetTarget >
template<>
struct DataType< ::hiwonder_interfaces::GetTargetRequest>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::GetTarget >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hiwonder_interfaces::GetTargetResponse> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::GetTarget >
template<>
struct MD5Sum< ::hiwonder_interfaces::GetTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::GetTarget >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::GetTargetResponse> should match
// service_traits::DataType< ::hiwonder_interfaces::GetTarget >
template<>
struct DataType< ::hiwonder_interfaces::GetTargetResponse>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::GetTarget >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_GETTARGET_H
