// Generated by gencpp from file hiwonder_interfaces/GetTargetResponse.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_GETTARGETRESPONSE_H
#define HIWONDER_INTERFACES_MESSAGE_GETTARGETRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct GetTargetResponse_
{
  typedef GetTargetResponse_<ContainerAllocator> Type;

  GetTargetResponse_()
    : success(false)
    , label()  {
    }
  GetTargetResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , label(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _label_type;
  _label_type label;





  typedef boost::shared_ptr< ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetTargetResponse_

typedef ::hiwonder_interfaces::GetTargetResponse_<std::allocator<void> > GetTargetResponse;

typedef boost::shared_ptr< ::hiwonder_interfaces::GetTargetResponse > GetTargetResponsePtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::GetTargetResponse const> GetTargetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.label == rhs.label;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a969347dbd0044352898c1217b7481aa";
  }

  static const char* value(const ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa969347dbd004435ULL;
  static const uint64_t static_value2 = 0x2898c1217b7481aaULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/GetTargetResponse";
  }

  static const char* value(const ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
"# 颜色标签，如'red', 'green', 'blue'\n"
"# 垃圾类别，如'BananaPeel'\n"
"string[] label\n"
"\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.label);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTargetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::GetTargetResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "label[]" << std::endl;
    for (size_t i = 0; i < v.label.size(); ++i)
    {
      s << indent << "  label[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.label[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_GETTARGETRESPONSE_H
