// Generated by gencpp from file hiwonder_interfaces/GraspState.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_GRASPSTATE_H
#define HIWONDER_INTERFACES_MESSAGE_GRASPSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hiwonder_interfaces/EulerAngles.h>

namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct GraspState_
{
  typedef GraspState_<ContainerAllocator> Type;

  GraspState_()
    : complete(false)
    , grasp_posture()  {
    }
  GraspState_(const ContainerAllocator& _alloc)
    : complete(false)
    , grasp_posture(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _complete_type;
  _complete_type complete;

   typedef  ::hiwonder_interfaces::EulerAngles_<ContainerAllocator>  _grasp_posture_type;
  _grasp_posture_type grasp_posture;





  typedef boost::shared_ptr< ::hiwonder_interfaces::GraspState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::GraspState_<ContainerAllocator> const> ConstPtr;

}; // struct GraspState_

typedef ::hiwonder_interfaces::GraspState_<std::allocator<void> > GraspState;

typedef boost::shared_ptr< ::hiwonder_interfaces::GraspState > GraspStatePtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::GraspState const> GraspStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::GraspState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::GraspState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::GraspState_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::GraspState_<ContainerAllocator2> & rhs)
{
  return lhs.complete == rhs.complete &&
    lhs.grasp_posture == rhs.grasp_posture;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::GraspState_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::GraspState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::GraspState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::GraspState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::GraspState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::GraspState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::GraspState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::GraspState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::GraspState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88fb84023fd99dd195825db77ccbd5b5";
  }

  static const char* value(const ::hiwonder_interfaces::GraspState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88fb84023fd99dd1ULL;
  static const uint64_t static_value2 = 0x95825db77ccbd5b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::GraspState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/GraspState";
  }

  static const char* value(const ::hiwonder_interfaces::GraspState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::GraspState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool complete\n"
"hiwonder_interfaces/EulerAngles grasp_posture\n"
"\n"
"================================================================================\n"
"MSG: hiwonder_interfaces/EulerAngles\n"
"float64 r\n"
"float64 p\n"
"float64 y\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::GraspState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::GraspState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.complete);
      stream.next(m.grasp_posture);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GraspState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::GraspState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::GraspState_<ContainerAllocator>& v)
  {
    s << indent << "complete: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.complete);
    s << indent << "grasp_posture: ";
    s << std::endl;
    Printer< ::hiwonder_interfaces::EulerAngles_<ContainerAllocator> >::stream(s, indent + "  ", v.grasp_posture);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_GRASPSTATE_H
