// Generated by gencpp from file hiwonder_interfaces/Grasp.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_GRASP_H
#define HIWONDER_INTERFACES_MESSAGE_GRASP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct Grasp_
{
  typedef Grasp_<ContainerAllocator> Type;

  Grasp_()
    : mode()
    , position()
    , pitch(0.0)
    , align_angle(0.0)
    , grasp_approach()
    , grasp_retreat()
    , grasp_posture(0)
    , pre_grasp_posture(0)  {
    }
  Grasp_(const ContainerAllocator& _alloc)
    : mode(_alloc)
    , position(_alloc)
    , pitch(0.0)
    , align_angle(0.0)
    , grasp_approach(_alloc)
    , grasp_retreat(_alloc)
    , grasp_posture(0)
    , pre_grasp_posture(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mode_type;
  _mode_type mode;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _align_angle_type;
  _align_angle_type align_angle;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _grasp_approach_type;
  _grasp_approach_type grasp_approach;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _grasp_retreat_type;
  _grasp_retreat_type grasp_retreat;

   typedef uint16_t _grasp_posture_type;
  _grasp_posture_type grasp_posture;

   typedef uint16_t _pre_grasp_posture_type;
  _pre_grasp_posture_type pre_grasp_posture;





  typedef boost::shared_ptr< ::hiwonder_interfaces::Grasp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::Grasp_<ContainerAllocator> const> ConstPtr;

}; // struct Grasp_

typedef ::hiwonder_interfaces::Grasp_<std::allocator<void> > Grasp;

typedef boost::shared_ptr< ::hiwonder_interfaces::Grasp > GraspPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::Grasp const> GraspConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::Grasp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::Grasp_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::Grasp_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::Grasp_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.position == rhs.position &&
    lhs.pitch == rhs.pitch &&
    lhs.align_angle == rhs.align_angle &&
    lhs.grasp_approach == rhs.grasp_approach &&
    lhs.grasp_retreat == rhs.grasp_retreat &&
    lhs.grasp_posture == rhs.grasp_posture &&
    lhs.pre_grasp_posture == rhs.pre_grasp_posture;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::Grasp_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::Grasp_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::Grasp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::Grasp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::Grasp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::Grasp_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::Grasp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::Grasp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::Grasp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e4e2be316d6a67c5705e66022e5a73c";
  }

  static const char* value(const ::hiwonder_interfaces::Grasp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e4e2be316d6a67cULL;
  static const uint64_t static_value2 = 0x5705e66022e5a73cULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::Grasp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/Grasp";
  }

  static const char* value(const ::hiwonder_interfaces::Grasp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::Grasp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# pick, place\n"
"string mode\n"
"\n"
"# 夹取时的姿态和位置\n"
"geometry_msgs/Point position\n"
"\n"
"float64 pitch\n"
"float64 align_angle\n"
"\n"
"# 接近时的距离和方向\n"
"geometry_msgs/Vector3 grasp_approach\n"
"\n"
"# 撤离时的距离和方向\n"
"geometry_msgs/Vector3 grasp_retreat\n"
"\n"
"# 夹取时夹持器姿态\n"
"uint16 grasp_posture\n"
"\n"
"# 夹取前夹持器姿态\n"
"uint16 pre_grasp_posture\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::Grasp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::Grasp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.position);
      stream.next(m.pitch);
      stream.next(m.align_angle);
      stream.next(m.grasp_approach);
      stream.next(m.grasp_retreat);
      stream.next(m.grasp_posture);
      stream.next(m.pre_grasp_posture);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Grasp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::Grasp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::Grasp_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mode);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "align_angle: ";
    Printer<double>::stream(s, indent + "  ", v.align_angle);
    s << indent << "grasp_approach: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.grasp_approach);
    s << indent << "grasp_retreat: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.grasp_retreat);
    s << indent << "grasp_posture: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.grasp_posture);
    s << indent << "pre_grasp_posture: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.pre_grasp_posture);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_GRASP_H
