// Generated by gencpp from file hiwonder_interfaces/JointMove.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_JOINTMOVE_H
#define HIWONDER_INTERFACES_MESSAGE_JOINTMOVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct JointMove_
{
  typedef JointMove_<ContainerAllocator> Type;

  JointMove_()
    : name()
    , rad(0.0)
    , duration(0.0)  {
    }
  JointMove_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , rad(0.0)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef double _rad_type;
  _rad_type rad;

   typedef double _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::hiwonder_interfaces::JointMove_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::JointMove_<ContainerAllocator> const> ConstPtr;

}; // struct JointMove_

typedef ::hiwonder_interfaces::JointMove_<std::allocator<void> > JointMove;

typedef boost::shared_ptr< ::hiwonder_interfaces::JointMove > JointMovePtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::JointMove const> JointMoveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::JointMove_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::JointMove_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::JointMove_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::JointMove_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.rad == rhs.rad &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::JointMove_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::JointMove_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::JointMove_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::JointMove_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::JointMove_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::JointMove_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::JointMove_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::JointMove_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::JointMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f79a23794e2d24d3d9bfad74299990fe";
  }

  static const char* value(const ::hiwonder_interfaces::JointMove_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf79a23794e2d24d3ULL;
  static const uint64_t static_value2 = 0xd9bfad74299990feULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::JointMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/JointMove";
  }

  static const char* value(const ::hiwonder_interfaces::JointMove_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::JointMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"float64 rad\n"
"float64 duration\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::JointMove_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::JointMove_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.rad);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointMove_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::JointMove_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::JointMove_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "rad: ";
    Printer<double>::stream(s, indent + "  ", v.rad);
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_JOINTMOVE_H
