// Generated by gencpp from file hiwonder_interfaces/Led.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_LED_H
#define HIWONDER_INTERFACES_MESSAGE_LED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct Led_
{
  typedef Led_<ContainerAllocator> Type;

  Led_()
    : brightness(0)
    , on_ticks(0)
    , off_ticks(0)
    , repeat(0)  {
    }
  Led_(const ContainerAllocator& _alloc)
    : brightness(0)
    , on_ticks(0)
    , off_ticks(0)
    , repeat(0)  {
  (void)_alloc;
    }



   typedef uint8_t _brightness_type;
  _brightness_type brightness;

   typedef uint16_t _on_ticks_type;
  _on_ticks_type on_ticks;

   typedef uint16_t _off_ticks_type;
  _off_ticks_type off_ticks;

   typedef uint16_t _repeat_type;
  _repeat_type repeat;





  typedef boost::shared_ptr< ::hiwonder_interfaces::Led_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::Led_<ContainerAllocator> const> ConstPtr;

}; // struct Led_

typedef ::hiwonder_interfaces::Led_<std::allocator<void> > Led;

typedef boost::shared_ptr< ::hiwonder_interfaces::Led > LedPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::Led const> LedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::Led_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::Led_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::Led_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::Led_<ContainerAllocator2> & rhs)
{
  return lhs.brightness == rhs.brightness &&
    lhs.on_ticks == rhs.on_ticks &&
    lhs.off_ticks == rhs.off_ticks &&
    lhs.repeat == rhs.repeat;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::Led_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::Led_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::Led_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::Led_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::Led_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::Led_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::Led_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::Led_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::Led_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d75341b887ccec081eae7150fd4708f";
  }

  static const char* value(const ::hiwonder_interfaces::Led_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d75341b887ccec0ULL;
  static const uint64_t static_value2 = 0x81eae7150fd4708fULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::Led_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/Led";
  }

  static const char* value(const ::hiwonder_interfaces::Led_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::Led_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8  brightness     # LED灯亮度\n"
"uint16 on_ticks       # LED亮起的时长 毫秒\n"
"uint16 off_ticks      # LED熄灭的时长 毫秒\n"
"uint16 repeat         # LED灯闪烁的重复次数\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::Led_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::Led_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.brightness);
      stream.next(m.on_ticks);
      stream.next(m.off_ticks);
      stream.next(m.repeat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Led_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::Led_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::Led_<ContainerAllocator>& v)
  {
    s << indent << "brightness: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brightness);
    s << indent << "on_ticks: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.on_ticks);
    s << indent << "off_ticks: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.off_ticks);
    s << indent << "repeat: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.repeat);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_LED_H
