// Generated by gencpp from file hiwonder_interfaces/MoveActionGoal.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_MOVEACTIONGOAL_H
#define HIWONDER_INTERFACES_MESSAGE_MOVEACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <hiwonder_interfaces/MoveGoal.h>

namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct MoveActionGoal_
{
  typedef MoveActionGoal_<ContainerAllocator> Type;

  MoveActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  MoveActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::hiwonder_interfaces::MoveGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MoveActionGoal_

typedef ::hiwonder_interfaces::MoveActionGoal_<std::allocator<void> > MoveActionGoal;

typedef boost::shared_ptr< ::hiwonder_interfaces::MoveActionGoal > MoveActionGoalPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::MoveActionGoal const> MoveActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34fe94cd8619371ab47af56450b1a95b";
  }

  static const char* value(const ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34fe94cd8619371aULL;
  static const uint64_t static_value2 = 0xb47af56450b1a95bULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/MoveActionGoal";
  }

  static const char* value(const ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"MoveGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: hiwonder_interfaces/MoveGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"hiwonder_interfaces/Grasp grasp\n"
"\n"
"================================================================================\n"
"MSG: hiwonder_interfaces/Grasp\n"
"# pick, place\n"
"string mode\n"
"\n"
"# 夹取时的姿态和位置\n"
"geometry_msgs/Point position\n"
"\n"
"float64 pitch\n"
"float64 align_angle\n"
"\n"
"# 接近时的距离和方向\n"
"geometry_msgs/Vector3 grasp_approach\n"
"\n"
"# 撤离时的距离和方向\n"
"geometry_msgs/Vector3 grasp_retreat\n"
"\n"
"# 夹取时夹持器姿态\n"
"uint16 grasp_posture\n"
"\n"
"# 夹取前夹持器姿态\n"
"uint16 pre_grasp_posture\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::MoveActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::hiwonder_interfaces::MoveGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_MOVEACTIONGOAL_H
