// Generated by gencpp from file hiwonder_interfaces/ObjectsInfo.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_OBJECTSINFO_H
#define HIWONDER_INTERFACES_MESSAGE_OBJECTSINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hiwonder_interfaces/ObjectInfo.h>

namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct ObjectsInfo_
{
  typedef ObjectsInfo_<ContainerAllocator> Type;

  ObjectsInfo_()
    : data()  {
    }
  ObjectsInfo_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectsInfo_

typedef ::hiwonder_interfaces::ObjectsInfo_<std::allocator<void> > ObjectsInfo;

typedef boost::shared_ptr< ::hiwonder_interfaces::ObjectsInfo > ObjectsInfoPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::ObjectsInfo const> ObjectsInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "44a9b7876b169d055c96381fead947aa";
  }

  static const char* value(const ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x44a9b7876b169d05ULL;
  static const uint64_t static_value2 = 0x5c96381fead947aaULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/ObjectsInfo";
  }

  static const char* value(const ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return " hiwonder_interfaces/ObjectInfo[] data\n"
"\n"
"================================================================================\n"
"MSG: hiwonder_interfaces/ObjectInfo\n"
"# 颜色标签，如'red1', 'green2', 'blue3', 'BananaPeel', 'BrokenBones'\n"
"string label\n"
"\n"
"# 物体的像素中心点坐标\n"
"hiwonder_interfaces/PixelPosition center\n"
"\n"
"# 物体的旋转角度，旋转角度指水平轴（x轴）逆时针旋转，与碰到的矩形的第一条边的夹角\n"
"int16 yaw\n"
"\n"
"# 物体图像尺寸\n"
"hiwonder_interfaces/ImageSize size\n"
"\n"
"# 物体高度 \n"
"float64 height\n"
"\n"
"================================================================================\n"
"MSG: hiwonder_interfaces/PixelPosition\n"
"uint16 x\n"
"uint16 y\n"
"\n"
"================================================================================\n"
"MSG: hiwonder_interfaces/ImageSize\n"
"uint16 width\n"
"uint16 height\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectsInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::ObjectsInfo_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_OBJECTSINFO_H
