// Generated by gencpp from file hiwonder_interfaces/ObjectInfo.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_OBJECTINFO_H
#define HIWONDER_INTERFACES_MESSAGE_OBJECTINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hiwonder_interfaces/PixelPosition.h>
#include <hiwonder_interfaces/ImageSize.h>

namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct ObjectInfo_
{
  typedef ObjectInfo_<ContainerAllocator> Type;

  ObjectInfo_()
    : label()
    , center()
    , yaw(0)
    , size()
    , height(0.0)  {
    }
  ObjectInfo_(const ContainerAllocator& _alloc)
    : label(_alloc)
    , center(_alloc)
    , yaw(0)
    , size(_alloc)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _label_type;
  _label_type label;

   typedef  ::hiwonder_interfaces::PixelPosition_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef int16_t _yaw_type;
  _yaw_type yaw;

   typedef  ::hiwonder_interfaces::ImageSize_<ContainerAllocator>  _size_type;
  _size_type size;

   typedef double _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectInfo_

typedef ::hiwonder_interfaces::ObjectInfo_<std::allocator<void> > ObjectInfo;

typedef boost::shared_ptr< ::hiwonder_interfaces::ObjectInfo > ObjectInfoPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::ObjectInfo const> ObjectInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator2> & rhs)
{
  return lhs.label == rhs.label &&
    lhs.center == rhs.center &&
    lhs.yaw == rhs.yaw &&
    lhs.size == rhs.size &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "334356fe136b15b91e4095edc296683b";
  }

  static const char* value(const ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x334356fe136b15b9ULL;
  static const uint64_t static_value2 = 0x1e4095edc296683bULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/ObjectInfo";
  }

  static const char* value(const ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 颜色标签，如'red1', 'green2', 'blue3', 'BananaPeel', 'BrokenBones'\n"
"string label\n"
"\n"
"# 物体的像素中心点坐标\n"
"hiwonder_interfaces/PixelPosition center\n"
"\n"
"# 物体的旋转角度，旋转角度指水平轴（x轴）逆时针旋转，与碰到的矩形的第一条边的夹角\n"
"int16 yaw\n"
"\n"
"# 物体图像尺寸\n"
"hiwonder_interfaces/ImageSize size\n"
"\n"
"# 物体高度 \n"
"float64 height\n"
"\n"
"================================================================================\n"
"MSG: hiwonder_interfaces/PixelPosition\n"
"uint16 x\n"
"uint16 y\n"
"\n"
"================================================================================\n"
"MSG: hiwonder_interfaces/ImageSize\n"
"uint16 width\n"
"uint16 height\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.center);
      stream.next(m.yaw);
      stream.next(m.size);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::ObjectInfo_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.label);
    s << indent << "center: ";
    s << std::endl;
    Printer< ::hiwonder_interfaces::PixelPosition_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    s << indent << "yaw: ";
    Printer<int16_t>::stream(s, indent + "  ", v.yaw);
    s << indent << "size: ";
    s << std::endl;
    Printer< ::hiwonder_interfaces::ImageSize_<ContainerAllocator> >::stream(s, indent + "  ", v.size);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_OBJECTINFO_H
