// Generated by gencpp from file hiwonder_interfaces/SerialServoTriggerRequest.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SERIALSERVOTRIGGERREQUEST_H
#define HIWONDER_INTERFACES_MESSAGE_SERIALSERVOTRIGGERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct SerialServoTriggerRequest_
{
  typedef SerialServoTriggerRequest_<ContainerAllocator> Type;

  SerialServoTriggerRequest_()
    : servo_id(0)  {
    }
  SerialServoTriggerRequest_(const ContainerAllocator& _alloc)
    : servo_id(0)  {
  (void)_alloc;
    }



   typedef uint8_t _servo_id_type;
  _servo_id_type servo_id;





  typedef boost::shared_ptr< ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SerialServoTriggerRequest_

typedef ::hiwonder_interfaces::SerialServoTriggerRequest_<std::allocator<void> > SerialServoTriggerRequest;

typedef boost::shared_ptr< ::hiwonder_interfaces::SerialServoTriggerRequest > SerialServoTriggerRequestPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::SerialServoTriggerRequest const> SerialServoTriggerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.servo_id == rhs.servo_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acb16072ea21cd71e884ac51239c2a0c";
  }

  static const char* value(const ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacb16072ea21cd71ULL;
  static const uint64_t static_value2 = 0xe884ac51239c2a0cULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/SerialServoTriggerRequest";
  }

  static const char* value(const ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 servo_id\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servo_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SerialServoTriggerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::SerialServoTriggerRequest_<ContainerAllocator>& v)
  {
    s << indent << "servo_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.servo_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SERIALSERVOTRIGGERREQUEST_H
