// Generated by gencpp from file hiwonder_interfaces/SerialServoMove.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SERIALSERVOMOVE_H
#define HIWONDER_INTERFACES_MESSAGE_SERIALSERVOMOVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct SerialServoMove_
{
  typedef SerialServoMove_<ContainerAllocator> Type;

  SerialServoMove_()
    : servo_id(0)
    , position(0)
    , duration(0)  {
    }
  SerialServoMove_(const ContainerAllocator& _alloc)
    : servo_id(0)
    , position(0)
    , duration(0)  {
  (void)_alloc;
    }



   typedef uint8_t _servo_id_type;
  _servo_id_type servo_id;

   typedef uint16_t _position_type;
  _position_type position;

   typedef uint16_t _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator> const> ConstPtr;

}; // struct SerialServoMove_

typedef ::hiwonder_interfaces::SerialServoMove_<std::allocator<void> > SerialServoMove;

typedef boost::shared_ptr< ::hiwonder_interfaces::SerialServoMove > SerialServoMovePtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::SerialServoMove const> SerialServoMoveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator2> & rhs)
{
  return lhs.servo_id == rhs.servo_id &&
    lhs.position == rhs.position &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5dc54bf167bb9c6046aadd2946345a2d";
  }

  static const char* value(const ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5dc54bf167bb9c60ULL;
  static const uint64_t static_value2 = 0x46aadd2946345a2dULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/SerialServoMove";
  }

  static const char* value(const ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 servo_id\n"
"uint16 position\n"
"uint16 duration\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servo_id);
      stream.next(m.position);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SerialServoMove_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::SerialServoMove_<ContainerAllocator>& v)
  {
    s << indent << "servo_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.servo_id);
    s << indent << "position: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.position);
    s << indent << "duration: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SERIALSERVOMOVE_H
