// Generated by gencpp from file hiwonder_interfaces/ServoState.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SERVOSTATE_H
#define HIWONDER_INTERFACES_MESSAGE_SERVOSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct ServoState_
{
  typedef ServoState_<ContainerAllocator> Type;

  ServoState_()
    : header()
    , timestamp(0.0)
    , id(0)
    , type(0)
    , goal(0)
    , position(0)
    , error(0)
    , voltage(0)  {
    }
  ServoState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , timestamp(0.0)
    , id(0)
    , type(0)
    , goal(0)
    , position(0)
    , error(0)
    , voltage(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _type_type;
  _type_type type;

   typedef int32_t _goal_type;
  _goal_type goal;

   typedef int32_t _position_type;
  _position_type position;

   typedef int32_t _error_type;
  _error_type error;

   typedef int32_t _voltage_type;
  _voltage_type voltage;





  typedef boost::shared_ptr< ::hiwonder_interfaces::ServoState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::ServoState_<ContainerAllocator> const> ConstPtr;

}; // struct ServoState_

typedef ::hiwonder_interfaces::ServoState_<std::allocator<void> > ServoState;

typedef boost::shared_ptr< ::hiwonder_interfaces::ServoState > ServoStatePtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::ServoState const> ServoStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::ServoState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::ServoState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::ServoState_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::ServoState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.timestamp == rhs.timestamp &&
    lhs.id == rhs.id &&
    lhs.type == rhs.type &&
    lhs.goal == rhs.goal &&
    lhs.position == rhs.position &&
    lhs.error == rhs.error &&
    lhs.voltage == rhs.voltage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::ServoState_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::ServoState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::ServoState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::ServoState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::ServoState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::ServoState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::ServoState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::ServoState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::ServoState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcd774646a3b4f67e60c7eb75c86da2c";
  }

  static const char* value(const ::hiwonder_interfaces::ServoState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdcd774646a3b4f67ULL;
  static const uint64_t static_value2 = 0xe60c7eb75c86da2cULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::ServoState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/ServoState";
  }

  static const char* value(const ::hiwonder_interfaces::ServoState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::ServoState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64 timestamp   # motor state is at this time\n"
"int32 id            # motor id\n"
"int32 type          # servo type\n"
"int32 goal          # commanded position (in encoder units)\n"
"int32 position      # current position (in encoder units)\n"
"int32 error         # difference between current and goal positions\n"
"int32 voltage       # current voltage (mv)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::ServoState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::ServoState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.timestamp);
      stream.next(m.id);
      stream.next(m.type);
      stream.next(m.goal);
      stream.next(m.position);
      stream.next(m.error);
      stream.next(m.voltage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::ServoState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::ServoState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.type);
    s << indent << "goal: ";
    Printer<int32_t>::stream(s, indent + "  ", v.goal);
    s << indent << "position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position);
    s << indent << "error: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error);
    s << indent << "voltage: ";
    Printer<int32_t>::stream(s, indent + "  ", v.voltage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SERVOSTATE_H
