// Generated by gencpp from file hiwonder_interfaces/ServoMove.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SERVOMOVE_H
#define HIWONDER_INTERFACES_MESSAGE_SERVOMOVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct ServoMove_
{
  typedef ServoMove_<ContainerAllocator> Type;

  ServoMove_()
    : id(0)
    , position(0)
    , duration(0.0)  {
    }
  ServoMove_(const ContainerAllocator& _alloc)
    : id(0)
    , position(0)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef int16_t _position_type;
  _position_type position;

   typedef double _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::hiwonder_interfaces::ServoMove_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::ServoMove_<ContainerAllocator> const> ConstPtr;

}; // struct ServoMove_

typedef ::hiwonder_interfaces::ServoMove_<std::allocator<void> > ServoMove;

typedef boost::shared_ptr< ::hiwonder_interfaces::ServoMove > ServoMovePtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::ServoMove const> ServoMoveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::ServoMove_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::ServoMove_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::ServoMove_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::ServoMove_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.position == rhs.position &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::ServoMove_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::ServoMove_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::ServoMove_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::ServoMove_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::ServoMove_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::ServoMove_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::ServoMove_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::ServoMove_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::ServoMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf5eb066650b015d3a13081e45341e52";
  }

  static const char* value(const ::hiwonder_interfaces::ServoMove_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf5eb066650b015dULL;
  static const uint64_t static_value2 = 0x3a13081e45341e52ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::ServoMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/ServoMove";
  }

  static const char* value(const ::hiwonder_interfaces::ServoMove_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::ServoMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"int16 position\n"
"float64 duration\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::ServoMove_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::ServoMove_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoMove_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::ServoMove_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::ServoMove_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "position: ";
    Printer<int16_t>::stream(s, indent + "  ", v.position);
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SERVOMOVE_H
