// Generated by gencpp from file hiwonder_interfaces/SetInt8Request.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SETINT8REQUEST_H
#define HIWONDER_INTERFACES_MESSAGE_SETINT8REQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct SetInt8Request_
{
  typedef SetInt8Request_<ContainerAllocator> Type;

  SetInt8Request_()
    : data(0)  {
    }
  SetInt8Request_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef int8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator> const> ConstPtr;

}; // struct SetInt8Request_

typedef ::hiwonder_interfaces::SetInt8Request_<std::allocator<void> > SetInt8Request;

typedef boost::shared_ptr< ::hiwonder_interfaces::SetInt8Request > SetInt8RequestPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::SetInt8Request const> SetInt8RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27ffa0c9c4b8fb8492252bcad9e5c57b";
  }

  static const char* value(const ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27ffa0c9c4b8fb84ULL;
  static const uint64_t static_value2 = 0x92252bcad9e5c57bULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/SetInt8Request";
  }

  static const char* value(const ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 data\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetInt8Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::SetInt8Request_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SETINT8REQUEST_H
