// Generated by gencpp from file hiwonder_interfaces/SetJointsValue.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SETJOINTSVALUE_H
#define HIWONDER_INTERFACES_MESSAGE_SETJOINTSVALUE_H

#include <ros/service_traits.h>


#include <hiwonder_interfaces/SetJointsValueRequest.h>
#include <hiwonder_interfaces/SetJointsValueResponse.h>


namespace hiwonder_interfaces
{

struct SetJointsValue
{

typedef SetJointsValueRequest Request;
typedef SetJointsValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointsValue
} // namespace hiwonder_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hiwonder_interfaces::SetJointsValue > {
  static const char* value()
  {
    return "29009da2011b752eb3bde0b041ee37ea";
  }

  static const char* value(const ::hiwonder_interfaces::SetJointsValue&) { return value(); }
};

template<>
struct DataType< ::hiwonder_interfaces::SetJointsValue > {
  static const char* value()
  {
    return "hiwonder_interfaces/SetJointsValue";
  }

  static const char* value(const ::hiwonder_interfaces::SetJointsValue&) { return value(); }
};


// service_traits::MD5Sum< ::hiwonder_interfaces::SetJointsValueRequest> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::SetJointsValue >
template<>
struct MD5Sum< ::hiwonder_interfaces::SetJointsValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::SetJointsValue >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetJointsValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::SetJointsValueRequest> should match
// service_traits::DataType< ::hiwonder_interfaces::SetJointsValue >
template<>
struct DataType< ::hiwonder_interfaces::SetJointsValueRequest>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::SetJointsValue >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetJointsValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hiwonder_interfaces::SetJointsValueResponse> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::SetJointsValue >
template<>
struct MD5Sum< ::hiwonder_interfaces::SetJointsValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::SetJointsValue >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetJointsValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::SetJointsValueResponse> should match
// service_traits::DataType< ::hiwonder_interfaces::SetJointsValue >
template<>
struct DataType< ::hiwonder_interfaces::SetJointsValueResponse>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::SetJointsValue >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetJointsValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SETJOINTSVALUE_H
