// Generated by gencpp from file hiwonder_interfaces/SetJointRangeRequest.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SETJOINTRANGEREQUEST_H
#define HIWONDER_INTERFACES_MESSAGE_SETJOINTRANGEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hiwonder_interfaces/JointsRange.h>

namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct SetJointRangeRequest_
{
  typedef SetJointRangeRequest_<ContainerAllocator> Type;

  SetJointRangeRequest_()
    : data()  {
    }
  SetJointRangeRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::hiwonder_interfaces::JointsRange_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetJointRangeRequest_

typedef ::hiwonder_interfaces::SetJointRangeRequest_<std::allocator<void> > SetJointRangeRequest;

typedef boost::shared_ptr< ::hiwonder_interfaces::SetJointRangeRequest > SetJointRangeRequestPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::SetJointRangeRequest const> SetJointRangeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b664c5dd4136dcf651b6709b837757e";
  }

  static const char* value(const ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b664c5dd4136dcfULL;
  static const uint64_t static_value2 = 0x651b6709b837757eULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/SetJointRangeRequest";
  }

  static const char* value(const ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/JointsRange data\n"
"\n"
"================================================================================\n"
"MSG: hiwonder_interfaces/JointsRange\n"
"hiwonder_interfaces/JointRange joint1\n"
"hiwonder_interfaces/JointRange joint2\n"
"hiwonder_interfaces/JointRange joint3\n"
"hiwonder_interfaces/JointRange joint4\n"
"hiwonder_interfaces/JointRange joint5\n"
"\n"
"================================================================================\n"
"MSG: hiwonder_interfaces/JointRange\n"
"float64 min\n"
"float64 max\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJointRangeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::SetJointRangeRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    s << std::endl;
    Printer< ::hiwonder_interfaces::JointsRange_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SETJOINTRANGEREQUEST_H
