// Generated by gencpp from file hiwonder_interfaces/SetJointValue.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SETJOINTVALUE_H
#define HIWONDER_INTERFACES_MESSAGE_SETJOINTVALUE_H

#include <ros/service_traits.h>


#include <hiwonder_interfaces/SetJointValueRequest.h>
#include <hiwonder_interfaces/SetJointValueResponse.h>


namespace hiwonder_interfaces
{

struct SetJointValue
{

typedef SetJointValueRequest Request;
typedef SetJointValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointValue
} // namespace hiwonder_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hiwonder_interfaces::SetJointValue > {
  static const char* value()
  {
    return "841f769c00b3378744250ae71b61c528";
  }

  static const char* value(const ::hiwonder_interfaces::SetJointValue&) { return value(); }
};

template<>
struct DataType< ::hiwonder_interfaces::SetJointValue > {
  static const char* value()
  {
    return "hiwonder_interfaces/SetJointValue";
  }

  static const char* value(const ::hiwonder_interfaces::SetJointValue&) { return value(); }
};


// service_traits::MD5Sum< ::hiwonder_interfaces::SetJointValueRequest> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::SetJointValue >
template<>
struct MD5Sum< ::hiwonder_interfaces::SetJointValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::SetJointValue >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetJointValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::SetJointValueRequest> should match
// service_traits::DataType< ::hiwonder_interfaces::SetJointValue >
template<>
struct DataType< ::hiwonder_interfaces::SetJointValueRequest>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::SetJointValue >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetJointValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hiwonder_interfaces::SetJointValueResponse> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::SetJointValue >
template<>
struct MD5Sum< ::hiwonder_interfaces::SetJointValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::SetJointValue >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetJointValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::SetJointValueResponse> should match
// service_traits::DataType< ::hiwonder_interfaces::SetJointValue >
template<>
struct DataType< ::hiwonder_interfaces::SetJointValueResponse>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::SetJointValue >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetJointValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SETJOINTVALUE_H
