// Generated by gencpp from file hiwonder_interfaces/SetLink.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SETLINK_H
#define HIWONDER_INTERFACES_MESSAGE_SETLINK_H

#include <ros/service_traits.h>


#include <hiwonder_interfaces/SetLinkRequest.h>
#include <hiwonder_interfaces/SetLinkResponse.h>


namespace hiwonder_interfaces
{

struct SetLink
{

typedef SetLinkRequest Request;
typedef SetLinkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLink
} // namespace hiwonder_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hiwonder_interfaces::SetLink > {
  static const char* value()
  {
    return "790e43afd8a9cb210768fe5732b22a83";
  }

  static const char* value(const ::hiwonder_interfaces::SetLink&) { return value(); }
};

template<>
struct DataType< ::hiwonder_interfaces::SetLink > {
  static const char* value()
  {
    return "hiwonder_interfaces/SetLink";
  }

  static const char* value(const ::hiwonder_interfaces::SetLink&) { return value(); }
};


// service_traits::MD5Sum< ::hiwonder_interfaces::SetLinkRequest> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::SetLink >
template<>
struct MD5Sum< ::hiwonder_interfaces::SetLinkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::SetLink >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetLinkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::SetLinkRequest> should match
// service_traits::DataType< ::hiwonder_interfaces::SetLink >
template<>
struct DataType< ::hiwonder_interfaces::SetLinkRequest>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::SetLink >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetLinkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hiwonder_interfaces::SetLinkResponse> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::SetLink >
template<>
struct MD5Sum< ::hiwonder_interfaces::SetLinkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::SetLink >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetLinkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::SetLinkResponse> should match
// service_traits::DataType< ::hiwonder_interfaces::SetLink >
template<>
struct DataType< ::hiwonder_interfaces::SetLinkResponse>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::SetLink >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetLinkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SETLINK_H
