// Generated by gencpp from file hiwonder_interfaces/SetPoseEuler.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SETPOSEEULER_H
#define HIWONDER_INTERFACES_MESSAGE_SETPOSEEULER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>

namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct SetPoseEuler_
{
  typedef SetPoseEuler_<ContainerAllocator> Type;

  SetPoseEuler_()
    : position()
    , orientation()
    , degrees(false)
    , duration(0.0)  {
    }
  SetPoseEuler_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , orientation(_alloc)
    , degrees(false)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef uint8_t _degrees_type;
  _degrees_type degrees;

   typedef double _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator> const> ConstPtr;

}; // struct SetPoseEuler_

typedef ::hiwonder_interfaces::SetPoseEuler_<std::allocator<void> > SetPoseEuler;

typedef boost::shared_ptr< ::hiwonder_interfaces::SetPoseEuler > SetPoseEulerPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::SetPoseEuler const> SetPoseEulerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.orientation == rhs.orientation &&
    lhs.degrees == rhs.degrees &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator> >
{
  static const char* value()
  {
    return "feee4cc50e0e73730e6b29ccee7649fa";
  }

  static const char* value(const ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfeee4cc50e0e7373ULL;
  static const uint64_t static_value2 = 0x0e6b29ccee7649faULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/SetPoseEuler";
  }

  static const char* value(const ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n"
"geometry_msgs/Vector3 orientation\n"
"bool degrees\n"
"float64 duration\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.orientation);
      stream.next(m.degrees);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPoseEuler_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::SetPoseEuler_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "degrees: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.degrees);
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SETPOSEEULER_H
