// Generated by gencpp from file hiwonder_interfaces/GetJointRangeResponse.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_GETJOINTRANGERESPONSE_H
#define HIWONDER_INTERFACES_MESSAGE_GETJOINTRANGERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hiwonder_interfaces/JointsRange.h>

namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct GetJointRangeResponse_
{
  typedef GetJointRangeResponse_<ContainerAllocator> Type;

  GetJointRangeResponse_()
    : success(false)
    , data()  {
    }
  GetJointRangeResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef  ::hiwonder_interfaces::JointsRange_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetJointRangeResponse_

typedef ::hiwonder_interfaces::GetJointRangeResponse_<std::allocator<void> > GetJointRangeResponse;

typedef boost::shared_ptr< ::hiwonder_interfaces::GetJointRangeResponse > GetJointRangeResponsePtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::GetJointRangeResponse const> GetJointRangeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33e6f68f335a1196c0815d29210eb550";
  }

  static const char* value(const ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33e6f68f335a1196ULL;
  static const uint64_t static_value2 = 0xc0815d29210eb550ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/GetJointRangeResponse";
  }

  static const char* value(const ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"hiwonder_interfaces/JointsRange data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: hiwonder_interfaces/JointsRange\n"
"hiwonder_interfaces/JointRange joint1\n"
"hiwonder_interfaces/JointRange joint2\n"
"hiwonder_interfaces/JointRange joint3\n"
"hiwonder_interfaces/JointRange joint4\n"
"hiwonder_interfaces/JointRange joint5\n"
"\n"
"================================================================================\n"
"MSG: hiwonder_interfaces/JointRange\n"
"float64 min\n"
"float64 max\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetJointRangeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::GetJointRangeResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "data: ";
    s << std::endl;
    Printer< ::hiwonder_interfaces::JointsRange_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_GETJOINTRANGERESPONSE_H
