// Generated by gencpp from file hiwonder_interfaces/GetJointRange.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_GETJOINTRANGE_H
#define HIWONDER_INTERFACES_MESSAGE_GETJOINTRANGE_H

#include <ros/service_traits.h>


#include <hiwonder_interfaces/GetJointRangeRequest.h>
#include <hiwonder_interfaces/GetJointRangeResponse.h>


namespace hiwonder_interfaces
{

struct GetJointRange
{

typedef GetJointRangeRequest Request;
typedef GetJointRangeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetJointRange
} // namespace hiwonder_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hiwonder_interfaces::GetJointRange > {
  static const char* value()
  {
    return "33e6f68f335a1196c0815d29210eb550";
  }

  static const char* value(const ::hiwonder_interfaces::GetJointRange&) { return value(); }
};

template<>
struct DataType< ::hiwonder_interfaces::GetJointRange > {
  static const char* value()
  {
    return "hiwonder_interfaces/GetJointRange";
  }

  static const char* value(const ::hiwonder_interfaces::GetJointRange&) { return value(); }
};


// service_traits::MD5Sum< ::hiwonder_interfaces::GetJointRangeRequest> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::GetJointRange >
template<>
struct MD5Sum< ::hiwonder_interfaces::GetJointRangeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::GetJointRange >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetJointRangeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::GetJointRangeRequest> should match
// service_traits::DataType< ::hiwonder_interfaces::GetJointRange >
template<>
struct DataType< ::hiwonder_interfaces::GetJointRangeRequest>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::GetJointRange >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetJointRangeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hiwonder_interfaces::GetJointRangeResponse> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::GetJointRange >
template<>
struct MD5Sum< ::hiwonder_interfaces::GetJointRangeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::GetJointRange >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetJointRangeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::GetJointRangeResponse> should match
// service_traits::DataType< ::hiwonder_interfaces::GetJointRange >
template<>
struct DataType< ::hiwonder_interfaces::GetJointRangeResponse>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::GetJointRange >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetJointRangeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_GETJOINTRANGE_H
