// Generated by gencpp from file hiwonder_interfaces/GetLinkRequest.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_GETLINKREQUEST_H
#define HIWONDER_INTERFACES_MESSAGE_GETLINKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct GetLinkRequest_
{
  typedef GetLinkRequest_<ContainerAllocator> Type;

  GetLinkRequest_()
    {
    }
  GetLinkRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetLinkRequest_

typedef ::hiwonder_interfaces::GetLinkRequest_<std::allocator<void> > GetLinkRequest;

typedef boost::shared_ptr< ::hiwonder_interfaces::GetLinkRequest > GetLinkRequestPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::GetLinkRequest const> GetLinkRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/GetLinkRequest";
  }

  static const char* value(const ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetLinkRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::hiwonder_interfaces::GetLinkRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_GETLINKREQUEST_H
