// Generated by gencpp from file hiwonder_interfaces/GetServoState.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_GETSERVOSTATE_H
#define HIWONDER_INTERFACES_MESSAGE_GETSERVOSTATE_H

#include <ros/service_traits.h>


#include <hiwonder_interfaces/GetServoStateRequest.h>
#include <hiwonder_interfaces/GetServoStateResponse.h>


namespace hiwonder_interfaces
{

struct GetServoState
{

typedef GetServoStateRequest Request;
typedef GetServoStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetServoState
} // namespace hiwonder_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hiwonder_interfaces::GetServoState > {
  static const char* value()
  {
    return "3f2b7dfd5e7d17f9fb64e9e86bb09ef2";
  }

  static const char* value(const ::hiwonder_interfaces::GetServoState&) { return value(); }
};

template<>
struct DataType< ::hiwonder_interfaces::GetServoState > {
  static const char* value()
  {
    return "hiwonder_interfaces/GetServoState";
  }

  static const char* value(const ::hiwonder_interfaces::GetServoState&) { return value(); }
};


// service_traits::MD5Sum< ::hiwonder_interfaces::GetServoStateRequest> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::GetServoState >
template<>
struct MD5Sum< ::hiwonder_interfaces::GetServoStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::GetServoState >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetServoStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::GetServoStateRequest> should match
// service_traits::DataType< ::hiwonder_interfaces::GetServoState >
template<>
struct DataType< ::hiwonder_interfaces::GetServoStateRequest>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::GetServoState >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetServoStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hiwonder_interfaces::GetServoStateResponse> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::GetServoState >
template<>
struct MD5Sum< ::hiwonder_interfaces::GetServoStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::GetServoState >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetServoStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::GetServoStateResponse> should match
// service_traits::DataType< ::hiwonder_interfaces::GetServoState >
template<>
struct DataType< ::hiwonder_interfaces::GetServoStateResponse>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::GetServoState >::value();
  }
  static const char* value(const ::hiwonder_interfaces::GetServoStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_GETSERVOSTATE_H
