// Generated by gencpp from file hiwonder_interfaces/ImageSize.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_IMAGESIZE_H
#define HIWONDER_INTERFACES_MESSAGE_IMAGESIZE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct ImageSize_
{
  typedef ImageSize_<ContainerAllocator> Type;

  ImageSize_()
    : width(0)
    , height(0)  {
    }
  ImageSize_(const ContainerAllocator& _alloc)
    : width(0)
    , height(0)  {
  (void)_alloc;
    }



   typedef uint16_t _width_type;
  _width_type width;

   typedef uint16_t _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::hiwonder_interfaces::ImageSize_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::ImageSize_<ContainerAllocator> const> ConstPtr;

}; // struct ImageSize_

typedef ::hiwonder_interfaces::ImageSize_<std::allocator<void> > ImageSize;

typedef boost::shared_ptr< ::hiwonder_interfaces::ImageSize > ImageSizePtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::ImageSize const> ImageSizeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::ImageSize_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::ImageSize_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::ImageSize_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::ImageSize_<ContainerAllocator2> & rhs)
{
  return lhs.width == rhs.width &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::ImageSize_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::ImageSize_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::ImageSize_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::ImageSize_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::ImageSize_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::ImageSize_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::ImageSize_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::ImageSize_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::ImageSize_<ContainerAllocator> >
{
  static const char* value()
  {
    return "20cde1cc3b01e7f015e45dc31f8ca17d";
  }

  static const char* value(const ::hiwonder_interfaces::ImageSize_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x20cde1cc3b01e7f0ULL;
  static const uint64_t static_value2 = 0x15e45dc31f8ca17dULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::ImageSize_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/ImageSize";
  }

  static const char* value(const ::hiwonder_interfaces::ImageSize_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::ImageSize_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 width\n"
"uint16 height\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::ImageSize_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::ImageSize_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageSize_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::ImageSize_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::ImageSize_<ContainerAllocator>& v)
  {
    s << indent << "width: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_IMAGESIZE_H
