// Generated by gencpp from file hiwonder_interfaces/JointsRange.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_JOINTSRANGE_H
#define HIWONDER_INTERFACES_MESSAGE_JOINTSRANGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hiwonder_interfaces/JointRange.h>
#include <hiwonder_interfaces/JointRange.h>
#include <hiwonder_interfaces/JointRange.h>
#include <hiwonder_interfaces/JointRange.h>
#include <hiwonder_interfaces/JointRange.h>

namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct JointsRange_
{
  typedef JointsRange_<ContainerAllocator> Type;

  JointsRange_()
    : joint1()
    , joint2()
    , joint3()
    , joint4()
    , joint5()  {
    }
  JointsRange_(const ContainerAllocator& _alloc)
    : joint1(_alloc)
    , joint2(_alloc)
    , joint3(_alloc)
    , joint4(_alloc)
    , joint5(_alloc)  {
  (void)_alloc;
    }



   typedef  ::hiwonder_interfaces::JointRange_<ContainerAllocator>  _joint1_type;
  _joint1_type joint1;

   typedef  ::hiwonder_interfaces::JointRange_<ContainerAllocator>  _joint2_type;
  _joint2_type joint2;

   typedef  ::hiwonder_interfaces::JointRange_<ContainerAllocator>  _joint3_type;
  _joint3_type joint3;

   typedef  ::hiwonder_interfaces::JointRange_<ContainerAllocator>  _joint4_type;
  _joint4_type joint4;

   typedef  ::hiwonder_interfaces::JointRange_<ContainerAllocator>  _joint5_type;
  _joint5_type joint5;





  typedef boost::shared_ptr< ::hiwonder_interfaces::JointsRange_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::JointsRange_<ContainerAllocator> const> ConstPtr;

}; // struct JointsRange_

typedef ::hiwonder_interfaces::JointsRange_<std::allocator<void> > JointsRange;

typedef boost::shared_ptr< ::hiwonder_interfaces::JointsRange > JointsRangePtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::JointsRange const> JointsRangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::JointsRange_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::JointsRange_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::JointsRange_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::JointsRange_<ContainerAllocator2> & rhs)
{
  return lhs.joint1 == rhs.joint1 &&
    lhs.joint2 == rhs.joint2 &&
    lhs.joint3 == rhs.joint3 &&
    lhs.joint4 == rhs.joint4 &&
    lhs.joint5 == rhs.joint5;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::JointsRange_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::JointsRange_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::JointsRange_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::JointsRange_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::JointsRange_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::JointsRange_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::JointsRange_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::JointsRange_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::JointsRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4756b6cbfe9dd3e05100c20e0ecd197";
  }

  static const char* value(const ::hiwonder_interfaces::JointsRange_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4756b6cbfe9dd3eULL;
  static const uint64_t static_value2 = 0x05100c20e0ecd197ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::JointsRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/JointsRange";
  }

  static const char* value(const ::hiwonder_interfaces::JointsRange_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::JointsRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/JointRange joint1\n"
"hiwonder_interfaces/JointRange joint2\n"
"hiwonder_interfaces/JointRange joint3\n"
"hiwonder_interfaces/JointRange joint4\n"
"hiwonder_interfaces/JointRange joint5\n"
"\n"
"================================================================================\n"
"MSG: hiwonder_interfaces/JointRange\n"
"float64 min\n"
"float64 max\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::JointsRange_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::JointsRange_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint1);
      stream.next(m.joint2);
      stream.next(m.joint3);
      stream.next(m.joint4);
      stream.next(m.joint5);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointsRange_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::JointsRange_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::JointsRange_<ContainerAllocator>& v)
  {
    s << indent << "joint1: ";
    s << std::endl;
    Printer< ::hiwonder_interfaces::JointRange_<ContainerAllocator> >::stream(s, indent + "  ", v.joint1);
    s << indent << "joint2: ";
    s << std::endl;
    Printer< ::hiwonder_interfaces::JointRange_<ContainerAllocator> >::stream(s, indent + "  ", v.joint2);
    s << indent << "joint3: ";
    s << std::endl;
    Printer< ::hiwonder_interfaces::JointRange_<ContainerAllocator> >::stream(s, indent + "  ", v.joint3);
    s << indent << "joint4: ";
    s << std::endl;
    Printer< ::hiwonder_interfaces::JointRange_<ContainerAllocator> >::stream(s, indent + "  ", v.joint4);
    s << indent << "joint5: ";
    s << std::endl;
    Printer< ::hiwonder_interfaces::JointRange_<ContainerAllocator> >::stream(s, indent + "  ", v.joint5);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_JOINTSRANGE_H
