// Generated by gencpp from file hiwonder_interfaces/JointRange.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_JOINTRANGE_H
#define HIWONDER_INTERFACES_MESSAGE_JOINTRANGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct JointRange_
{
  typedef JointRange_<ContainerAllocator> Type;

  JointRange_()
    : min(0.0)
    , max(0.0)  {
    }
  JointRange_(const ContainerAllocator& _alloc)
    : min(0.0)
    , max(0.0)  {
  (void)_alloc;
    }



   typedef double _min_type;
  _min_type min;

   typedef double _max_type;
  _max_type max;





  typedef boost::shared_ptr< ::hiwonder_interfaces::JointRange_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::JointRange_<ContainerAllocator> const> ConstPtr;

}; // struct JointRange_

typedef ::hiwonder_interfaces::JointRange_<std::allocator<void> > JointRange;

typedef boost::shared_ptr< ::hiwonder_interfaces::JointRange > JointRangePtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::JointRange const> JointRangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::JointRange_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::JointRange_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::JointRange_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::JointRange_<ContainerAllocator2> & rhs)
{
  return lhs.min == rhs.min &&
    lhs.max == rhs.max;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::JointRange_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::JointRange_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::JointRange_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::JointRange_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::JointRange_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::JointRange_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::JointRange_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::JointRange_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::JointRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32e1c0b6f254bb48e963512143e9aa6f";
  }

  static const char* value(const ::hiwonder_interfaces::JointRange_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32e1c0b6f254bb48ULL;
  static const uint64_t static_value2 = 0xe963512143e9aa6fULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::JointRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/JointRange";
  }

  static const char* value(const ::hiwonder_interfaces::JointRange_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::JointRange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 min\n"
"float64 max\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::JointRange_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::JointRange_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.min);
      stream.next(m.max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointRange_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::JointRange_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::JointRange_<ContainerAllocator>& v)
  {
    s << indent << "min: ";
    Printer<double>::stream(s, indent + "  ", v.min);
    s << indent << "max: ";
    Printer<double>::stream(s, indent + "  ", v.max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_JOINTRANGE_H
