// Generated by gencpp from file hiwonder_interfaces/Link.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_LINK_H
#define HIWONDER_INTERFACES_MESSAGE_LINK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct Link_
{
  typedef Link_<ContainerAllocator> Type;

  Link_()
    : base_link(0.0)
    , link1(0.0)
    , link2(0.0)
    , link3(0.0)
    , end_effector_link(0.0)  {
    }
  Link_(const ContainerAllocator& _alloc)
    : base_link(0.0)
    , link1(0.0)
    , link2(0.0)
    , link3(0.0)
    , end_effector_link(0.0)  {
  (void)_alloc;
    }



   typedef double _base_link_type;
  _base_link_type base_link;

   typedef double _link1_type;
  _link1_type link1;

   typedef double _link2_type;
  _link2_type link2;

   typedef double _link3_type;
  _link3_type link3;

   typedef double _end_effector_link_type;
  _end_effector_link_type end_effector_link;





  typedef boost::shared_ptr< ::hiwonder_interfaces::Link_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::Link_<ContainerAllocator> const> ConstPtr;

}; // struct Link_

typedef ::hiwonder_interfaces::Link_<std::allocator<void> > Link;

typedef boost::shared_ptr< ::hiwonder_interfaces::Link > LinkPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::Link const> LinkConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::Link_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::Link_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::Link_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::Link_<ContainerAllocator2> & rhs)
{
  return lhs.base_link == rhs.base_link &&
    lhs.link1 == rhs.link1 &&
    lhs.link2 == rhs.link2 &&
    lhs.link3 == rhs.link3 &&
    lhs.end_effector_link == rhs.end_effector_link;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::Link_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::Link_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::Link_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::Link_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::Link_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::Link_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::Link_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::Link_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::Link_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee67099c892ac23d92388e7b3fe65a55";
  }

  static const char* value(const ::hiwonder_interfaces::Link_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee67099c892ac23dULL;
  static const uint64_t static_value2 = 0x92388e7b3fe65a55ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::Link_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/Link";
  }

  static const char* value(const ::hiwonder_interfaces::Link_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::Link_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 base_link\n"
"float64 link1\n"
"float64 link2\n"
"float64 link3\n"
"float64 end_effector_link\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::Link_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::Link_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.base_link);
      stream.next(m.link1);
      stream.next(m.link2);
      stream.next(m.link3);
      stream.next(m.end_effector_link);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Link_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::Link_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::Link_<ContainerAllocator>& v)
  {
    s << indent << "base_link: ";
    Printer<double>::stream(s, indent + "  ", v.base_link);
    s << indent << "link1: ";
    Printer<double>::stream(s, indent + "  ", v.link1);
    s << indent << "link2: ";
    Printer<double>::stream(s, indent + "  ", v.link2);
    s << indent << "link3: ";
    Printer<double>::stream(s, indent + "  ", v.link3);
    s << indent << "end_effector_link: ";
    Printer<double>::stream(s, indent + "  ", v.end_effector_link);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_LINK_H
