// Generated by gencpp from file hiwonder_interfaces/MoveFeedback.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_MOVEFEEDBACK_H
#define HIWONDER_INTERFACES_MESSAGE_MOVEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct MoveFeedback_
{
  typedef MoveFeedback_<ContainerAllocator> Type;

  MoveFeedback_()
    : percent(0.0)  {
    }
  MoveFeedback_(const ContainerAllocator& _alloc)
    : percent(0.0)  {
  (void)_alloc;
    }



   typedef double _percent_type;
  _percent_type percent;





  typedef boost::shared_ptr< ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MoveFeedback_

typedef ::hiwonder_interfaces::MoveFeedback_<std::allocator<void> > MoveFeedback;

typedef boost::shared_ptr< ::hiwonder_interfaces::MoveFeedback > MoveFeedbackPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::MoveFeedback const> MoveFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percent == rhs.percent;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6e607cac4f6b2d41392a1a3b72e4390";
  }

  static const char* value(const ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6e607cac4f6b2d4ULL;
  static const uint64_t static_value2 = 0x1392a1a3b72e4390ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/MoveFeedback";
  }

  static const char* value(const ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float64 percent\n"
"\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::MoveFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percent: ";
    Printer<double>::stream(s, indent + "  ", v.percent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_MOVEFEEDBACK_H
