// Generated by gencpp from file hiwonder_interfaces/MoveGoal.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_MOVEGOAL_H
#define HIWONDER_INTERFACES_MESSAGE_MOVEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hiwonder_interfaces/Grasp.h>

namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct MoveGoal_
{
  typedef MoveGoal_<ContainerAllocator> Type;

  MoveGoal_()
    : grasp()  {
    }
  MoveGoal_(const ContainerAllocator& _alloc)
    : grasp(_alloc)  {
  (void)_alloc;
    }



   typedef  ::hiwonder_interfaces::Grasp_<ContainerAllocator>  _grasp_type;
  _grasp_type grasp;





  typedef boost::shared_ptr< ::hiwonder_interfaces::MoveGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::MoveGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MoveGoal_

typedef ::hiwonder_interfaces::MoveGoal_<std::allocator<void> > MoveGoal;

typedef boost::shared_ptr< ::hiwonder_interfaces::MoveGoal > MoveGoalPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::MoveGoal const> MoveGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::MoveGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::MoveGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::MoveGoal_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::MoveGoal_<ContainerAllocator2> & rhs)
{
  return lhs.grasp == rhs.grasp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::MoveGoal_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::MoveGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::MoveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::MoveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::MoveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::MoveGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::MoveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::MoveGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::MoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e8dc9d50c716c29037a12241ed7c244";
  }

  static const char* value(const ::hiwonder_interfaces::MoveGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e8dc9d50c716c29ULL;
  static const uint64_t static_value2 = 0x037a12241ed7c244ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::MoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/MoveGoal";
  }

  static const char* value(const ::hiwonder_interfaces::MoveGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::MoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"hiwonder_interfaces/Grasp grasp\n"
"\n"
"================================================================================\n"
"MSG: hiwonder_interfaces/Grasp\n"
"# pick, place\n"
"string mode\n"
"\n"
"# 夹取时的姿态和位置\n"
"geometry_msgs/Point position\n"
"\n"
"float64 pitch\n"
"float64 align_angle\n"
"\n"
"# 接近时的距离和方向\n"
"geometry_msgs/Vector3 grasp_approach\n"
"\n"
"# 撤离时的距离和方向\n"
"geometry_msgs/Vector3 grasp_retreat\n"
"\n"
"# 夹取时夹持器姿态\n"
"uint16 grasp_posture\n"
"\n"
"# 夹取前夹持器姿态\n"
"uint16 pre_grasp_posture\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::MoveGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::MoveGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grasp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::MoveGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::MoveGoal_<ContainerAllocator>& v)
  {
    s << indent << "grasp: ";
    s << std::endl;
    Printer< ::hiwonder_interfaces::Grasp_<ContainerAllocator> >::stream(s, indent + "  ", v.grasp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_MOVEGOAL_H
