// Generated by gencpp from file hiwonder_interfaces/MoveResult.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_MOVERESULT_H
#define HIWONDER_INTERFACES_MESSAGE_MOVERESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hiwonder_interfaces/GraspState.h>

namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct MoveResult_
{
  typedef MoveResult_<ContainerAllocator> Type;

  MoveResult_()
    : result()  {
    }
  MoveResult_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef  ::hiwonder_interfaces::GraspState_<ContainerAllocator>  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::hiwonder_interfaces::MoveResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::MoveResult_<ContainerAllocator> const> ConstPtr;

}; // struct MoveResult_

typedef ::hiwonder_interfaces::MoveResult_<std::allocator<void> > MoveResult;

typedef boost::shared_ptr< ::hiwonder_interfaces::MoveResult > MoveResultPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::MoveResult const> MoveResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::MoveResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::MoveResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::MoveResult_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::MoveResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::MoveResult_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::MoveResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::MoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::MoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::MoveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::MoveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::MoveResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::MoveResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::MoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee1ee077361bf11d478f1e601fee6a92";
  }

  static const char* value(const ::hiwonder_interfaces::MoveResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee1ee077361bf11dULL;
  static const uint64_t static_value2 = 0x478f1e601fee6a92ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::MoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/MoveResult";
  }

  static const char* value(const ::hiwonder_interfaces::MoveResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::MoveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"hiwonder_interfaces/GraspState result\n"
"\n"
"================================================================================\n"
"MSG: hiwonder_interfaces/GraspState\n"
"bool complete\n"
"hiwonder_interfaces/EulerAngles grasp_posture\n"
"\n"
"================================================================================\n"
"MSG: hiwonder_interfaces/EulerAngles\n"
"float64 r\n"
"float64 p\n"
"float64 y\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::MoveResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::MoveResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::MoveResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::MoveResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    s << std::endl;
    Printer< ::hiwonder_interfaces::GraspState_<ContainerAllocator> >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_MOVERESULT_H
