// Generated by gencpp from file hiwonder_interfaces/PixelPosition.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_PIXELPOSITION_H
#define HIWONDER_INTERFACES_MESSAGE_PIXELPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct PixelPosition_
{
  typedef PixelPosition_<ContainerAllocator> Type;

  PixelPosition_()
    : x(0)
    , y(0)  {
    }
  PixelPosition_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef uint16_t _x_type;
  _x_type x;

   typedef uint16_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::hiwonder_interfaces::PixelPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::PixelPosition_<ContainerAllocator> const> ConstPtr;

}; // struct PixelPosition_

typedef ::hiwonder_interfaces::PixelPosition_<std::allocator<void> > PixelPosition;

typedef boost::shared_ptr< ::hiwonder_interfaces::PixelPosition > PixelPositionPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::PixelPosition const> PixelPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::PixelPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::PixelPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::PixelPosition_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::PixelPosition_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::PixelPosition_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::PixelPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::PixelPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::PixelPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::PixelPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::PixelPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::PixelPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::PixelPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::PixelPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b80853b9dd76da1c3efb4dbc2426fe9";
  }

  static const char* value(const ::hiwonder_interfaces::PixelPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b80853b9dd76da1ULL;
  static const uint64_t static_value2 = 0xc3efb4dbc2426fe9ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::PixelPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/PixelPosition";
  }

  static const char* value(const ::hiwonder_interfaces::PixelPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::PixelPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 x\n"
"uint16 y\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::PixelPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::PixelPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PixelPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::PixelPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::PixelPosition_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_PIXELPOSITION_H
