// Generated by gencpp from file hiwonder_interfaces/SerialServoTrigger.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SERIALSERVOTRIGGER_H
#define HIWONDER_INTERFACES_MESSAGE_SERIALSERVOTRIGGER_H

#include <ros/service_traits.h>


#include <hiwonder_interfaces/SerialServoTriggerRequest.h>
#include <hiwonder_interfaces/SerialServoTriggerResponse.h>


namespace hiwonder_interfaces
{

struct SerialServoTrigger
{

typedef SerialServoTriggerRequest Request;
typedef SerialServoTriggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SerialServoTrigger
} // namespace hiwonder_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hiwonder_interfaces::SerialServoTrigger > {
  static const char* value()
  {
    return "5f5091eac81f15b2ecca9496c10bde6a";
  }

  static const char* value(const ::hiwonder_interfaces::SerialServoTrigger&) { return value(); }
};

template<>
struct DataType< ::hiwonder_interfaces::SerialServoTrigger > {
  static const char* value()
  {
    return "hiwonder_interfaces/SerialServoTrigger";
  }

  static const char* value(const ::hiwonder_interfaces::SerialServoTrigger&) { return value(); }
};


// service_traits::MD5Sum< ::hiwonder_interfaces::SerialServoTriggerRequest> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::SerialServoTrigger >
template<>
struct MD5Sum< ::hiwonder_interfaces::SerialServoTriggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::SerialServoTrigger >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SerialServoTriggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::SerialServoTriggerRequest> should match
// service_traits::DataType< ::hiwonder_interfaces::SerialServoTrigger >
template<>
struct DataType< ::hiwonder_interfaces::SerialServoTriggerRequest>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::SerialServoTrigger >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SerialServoTriggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hiwonder_interfaces::SerialServoTriggerResponse> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::SerialServoTrigger >
template<>
struct MD5Sum< ::hiwonder_interfaces::SerialServoTriggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::SerialServoTrigger >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SerialServoTriggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::SerialServoTriggerResponse> should match
// service_traits::DataType< ::hiwonder_interfaces::SerialServoTrigger >
template<>
struct DataType< ::hiwonder_interfaces::SerialServoTriggerResponse>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::SerialServoTrigger >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SerialServoTriggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SERIALSERVOTRIGGER_H
