// Generated by gencpp from file hiwonder_interfaces/SerialServoBool.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SERIALSERVOBOOL_H
#define HIWONDER_INTERFACES_MESSAGE_SERIALSERVOBOOL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct SerialServoBool_
{
  typedef SerialServoBool_<ContainerAllocator> Type;

  SerialServoBool_()
    : servo_id(0)
    , state(false)  {
    }
  SerialServoBool_(const ContainerAllocator& _alloc)
    : servo_id(0)
    , state(false)  {
  (void)_alloc;
    }



   typedef uint8_t _servo_id_type;
  _servo_id_type servo_id;

   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator> const> ConstPtr;

}; // struct SerialServoBool_

typedef ::hiwonder_interfaces::SerialServoBool_<std::allocator<void> > SerialServoBool;

typedef boost::shared_ptr< ::hiwonder_interfaces::SerialServoBool > SerialServoBoolPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::SerialServoBool const> SerialServoBoolConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator2> & rhs)
{
  return lhs.servo_id == rhs.servo_id &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d73ace136d2944106a7cfcfd261a5b9a";
  }

  static const char* value(const ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd73ace136d294410ULL;
  static const uint64_t static_value2 = 0x6a7cfcfd261a5b9aULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/SerialServoBool";
  }

  static const char* value(const ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 servo_id\n"
"bool  state\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servo_id);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SerialServoBool_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::SerialServoBool_<ContainerAllocator>& v)
  {
    s << indent << "servo_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.servo_id);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SERIALSERVOBOOL_H
