// Generated by gencpp from file hiwonder_interfaces/ServoStateList.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SERVOSTATELIST_H
#define HIWONDER_INTERFACES_MESSAGE_SERVOSTATELIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <hiwonder_interfaces/ServoState.h>

namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct ServoStateList_
{
  typedef ServoStateList_<ContainerAllocator> Type;

  ServoStateList_()
    : header()
    , servo_states()  {
    }
  ServoStateList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , servo_states(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::hiwonder_interfaces::ServoState_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::hiwonder_interfaces::ServoState_<ContainerAllocator> >> _servo_states_type;
  _servo_states_type servo_states;





  typedef boost::shared_ptr< ::hiwonder_interfaces::ServoStateList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::ServoStateList_<ContainerAllocator> const> ConstPtr;

}; // struct ServoStateList_

typedef ::hiwonder_interfaces::ServoStateList_<std::allocator<void> > ServoStateList;

typedef boost::shared_ptr< ::hiwonder_interfaces::ServoStateList > ServoStateListPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::ServoStateList const> ServoStateListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::ServoStateList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::ServoStateList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::ServoStateList_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::ServoStateList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.servo_states == rhs.servo_states;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::ServoStateList_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::ServoStateList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::ServoStateList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::ServoStateList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::ServoStateList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::ServoStateList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::ServoStateList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::ServoStateList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::ServoStateList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22e881eeaee8270c42551f7b1f39e386";
  }

  static const char* value(const ::hiwonder_interfaces::ServoStateList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22e881eeaee8270cULL;
  static const uint64_t static_value2 = 0x42551f7b1f39e386ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::ServoStateList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/ServoStateList";
  }

  static const char* value(const ::hiwonder_interfaces::ServoStateList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::ServoStateList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"ServoState[] servo_states\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: hiwonder_interfaces/ServoState\n"
"std_msgs/Header header\n"
"float64 timestamp   # motor state is at this time\n"
"int32 id            # motor id\n"
"int32 type          # servo type\n"
"int32 goal          # commanded position (in encoder units)\n"
"int32 position      # current position (in encoder units)\n"
"int32 error         # difference between current and goal positions\n"
"int32 voltage       # current voltage (mv)\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::ServoStateList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::ServoStateList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.servo_states);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoStateList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::ServoStateList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::ServoStateList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "servo_states[]" << std::endl;
    for (size_t i = 0; i < v.servo_states.size(); ++i)
    {
      s << indent << "  servo_states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hiwonder_interfaces::ServoState_<ContainerAllocator> >::stream(s, indent + "    ", v.servo_states[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SERVOSTATELIST_H
