// Generated by gencpp from file hiwonder_interfaces/SetInt8.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SETINT8_H
#define HIWONDER_INTERFACES_MESSAGE_SETINT8_H

#include <ros/service_traits.h>


#include <hiwonder_interfaces/SetInt8Request.h>
#include <hiwonder_interfaces/SetInt8Response.h>


namespace hiwonder_interfaces
{

struct SetInt8
{

typedef SetInt8Request Request;
typedef SetInt8Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetInt8
} // namespace hiwonder_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hiwonder_interfaces::SetInt8 > {
  static const char* value()
  {
    return "208d4ab53cf12eb941a7d93b34b7532b";
  }

  static const char* value(const ::hiwonder_interfaces::SetInt8&) { return value(); }
};

template<>
struct DataType< ::hiwonder_interfaces::SetInt8 > {
  static const char* value()
  {
    return "hiwonder_interfaces/SetInt8";
  }

  static const char* value(const ::hiwonder_interfaces::SetInt8&) { return value(); }
};


// service_traits::MD5Sum< ::hiwonder_interfaces::SetInt8Request> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::SetInt8 >
template<>
struct MD5Sum< ::hiwonder_interfaces::SetInt8Request>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::SetInt8 >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetInt8Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::SetInt8Request> should match
// service_traits::DataType< ::hiwonder_interfaces::SetInt8 >
template<>
struct DataType< ::hiwonder_interfaces::SetInt8Request>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::SetInt8 >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetInt8Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hiwonder_interfaces::SetInt8Response> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::SetInt8 >
template<>
struct MD5Sum< ::hiwonder_interfaces::SetInt8Response>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::SetInt8 >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetInt8Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::SetInt8Response> should match
// service_traits::DataType< ::hiwonder_interfaces::SetInt8 >
template<>
struct DataType< ::hiwonder_interfaces::SetInt8Response>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::SetInt8 >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetInt8Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SETINT8_H
