// Generated by gencpp from file hiwonder_interfaces/SetJointValueRequest.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SETJOINTVALUEREQUEST_H
#define HIWONDER_INTERFACES_MESSAGE_SETJOINTVALUEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct SetJointValueRequest_
{
  typedef SetJointValueRequest_<ContainerAllocator> Type;

  SetJointValueRequest_()
    : joint_value()  {
    }
  SetJointValueRequest_(const ContainerAllocator& _alloc)
    : joint_value(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _joint_value_type;
  _joint_value_type joint_value;





  typedef boost::shared_ptr< ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetJointValueRequest_

typedef ::hiwonder_interfaces::SetJointValueRequest_<std::allocator<void> > SetJointValueRequest;

typedef boost::shared_ptr< ::hiwonder_interfaces::SetJointValueRequest > SetJointValueRequestPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::SetJointValueRequest const> SetJointValueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joint_value == rhs.joint_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97ed8712ead473224aec3bee8e7849e0";
  }

  static const char* value(const ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97ed8712ead47322ULL;
  static const uint64_t static_value2 = 0x4aec3bee8e7849e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/SetJointValueRequest";
  }

  static const char* value(const ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] joint_value\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJointValueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::SetJointValueRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_value[]" << std::endl;
    for (size_t i = 0; i < v.joint_value.size(); ++i)
    {
      s << indent << "  joint_value[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joint_value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SETJOINTVALUEREQUEST_H
