// Generated by gencpp from file hiwonder_interfaces/SetJointsValueRequest.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SETJOINTSVALUEREQUEST_H
#define HIWONDER_INTERFACES_MESSAGE_SETJOINTSVALUEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct SetJointsValueRequest_
{
  typedef SetJointsValueRequest_<ContainerAllocator> Type;

  SetJointsValueRequest_()
    : joints_value()  {
    }
  SetJointsValueRequest_(const ContainerAllocator& _alloc)
    : joints_value(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _joints_value_type;
  _joints_value_type joints_value;





  typedef boost::shared_ptr< ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetJointsValueRequest_

typedef ::hiwonder_interfaces::SetJointsValueRequest_<std::allocator<void> > SetJointsValueRequest;

typedef boost::shared_ptr< ::hiwonder_interfaces::SetJointsValueRequest > SetJointsValueRequestPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::SetJointsValueRequest const> SetJointsValueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joints_value == rhs.joints_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8afdbabd94ac8ced8aade445e5b17386";
  }

  static const char* value(const ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8afdbabd94ac8cedULL;
  static const uint64_t static_value2 = 0x8aade445e5b17386ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/SetJointsValueRequest";
  }

  static const char* value(const ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] joints_value\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJointsValueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::SetJointsValueRequest_<ContainerAllocator>& v)
  {
    s << indent << "joints_value[]" << std::endl;
    for (size_t i = 0; i < v.joints_value.size(); ++i)
    {
      s << indent << "  joints_value[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joints_value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SETJOINTSVALUEREQUEST_H
