// Generated by gencpp from file hiwonder_interfaces/SetJointRange.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SETJOINTRANGE_H
#define HIWONDER_INTERFACES_MESSAGE_SETJOINTRANGE_H

#include <ros/service_traits.h>


#include <hiwonder_interfaces/SetJointRangeRequest.h>
#include <hiwonder_interfaces/SetJointRangeResponse.h>


namespace hiwonder_interfaces
{

struct SetJointRange
{

typedef SetJointRangeRequest Request;
typedef SetJointRangeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointRange
} // namespace hiwonder_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hiwonder_interfaces::SetJointRange > {
  static const char* value()
  {
    return "650ce1142907ebb9d989246f5b6eb1fe";
  }

  static const char* value(const ::hiwonder_interfaces::SetJointRange&) { return value(); }
};

template<>
struct DataType< ::hiwonder_interfaces::SetJointRange > {
  static const char* value()
  {
    return "hiwonder_interfaces/SetJointRange";
  }

  static const char* value(const ::hiwonder_interfaces::SetJointRange&) { return value(); }
};


// service_traits::MD5Sum< ::hiwonder_interfaces::SetJointRangeRequest> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::SetJointRange >
template<>
struct MD5Sum< ::hiwonder_interfaces::SetJointRangeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::SetJointRange >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetJointRangeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::SetJointRangeRequest> should match
// service_traits::DataType< ::hiwonder_interfaces::SetJointRange >
template<>
struct DataType< ::hiwonder_interfaces::SetJointRangeRequest>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::SetJointRange >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetJointRangeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hiwonder_interfaces::SetJointRangeResponse> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::SetJointRange >
template<>
struct MD5Sum< ::hiwonder_interfaces::SetJointRangeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::SetJointRange >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetJointRangeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::SetJointRangeResponse> should match
// service_traits::DataType< ::hiwonder_interfaces::SetJointRange >
template<>
struct DataType< ::hiwonder_interfaces::SetJointRangeResponse>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::SetJointRange >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetJointRangeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SETJOINTRANGE_H
