// Generated by gencpp from file hiwonder_interfaces/SetPose.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SETPOSE_H
#define HIWONDER_INTERFACES_MESSAGE_SETPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Quaternion.h>

namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct SetPose_
{
  typedef SetPose_<ContainerAllocator> Type;

  SetPose_()
    : position()
    , orientation()
    , duration(0.0)  {
    }
  SetPose_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , orientation(_alloc)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef double _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::hiwonder_interfaces::SetPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::SetPose_<ContainerAllocator> const> ConstPtr;

}; // struct SetPose_

typedef ::hiwonder_interfaces::SetPose_<std::allocator<void> > SetPose;

typedef boost::shared_ptr< ::hiwonder_interfaces::SetPose > SetPosePtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::SetPose const> SetPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::SetPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::SetPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::SetPose_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetPose_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.orientation == rhs.orientation &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::SetPose_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::SetPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1115bc6fab88feb8756506ed89e5a634";
  }

  static const char* value(const ::hiwonder_interfaces::SetPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1115bc6fab88feb8ULL;
  static const uint64_t static_value2 = 0x756506ed89e5a634ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::SetPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/SetPose";
  }

  static const char* value(const ::hiwonder_interfaces::SetPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::SetPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n"
"geometry_msgs/Quaternion orientation\n"
"float64 duration\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::SetPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::SetPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.orientation);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::SetPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::SetPose_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SETPOSE_H
