// Generated by gencpp from file hiwonder_interfaces/SetRobotPoseResponse.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SETROBOTPOSERESPONSE_H
#define HIWONDER_INTERFACES_MESSAGE_SETROBOTPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct SetRobotPoseResponse_
{
  typedef SetRobotPoseResponse_<ContainerAllocator> Type;

  SetRobotPoseResponse_()
    : success(false)
    , pulse()
    , current_pulse()
    , rpy()
    , min_variation(0.0)  {
    }
  SetRobotPoseResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , pulse(_alloc)
    , current_pulse(_alloc)
    , rpy(_alloc)
    , min_variation(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _pulse_type;
  _pulse_type pulse;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _current_pulse_type;
  _current_pulse_type current_pulse;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _rpy_type;
  _rpy_type rpy;

   typedef double _min_variation_type;
  _min_variation_type min_variation;





  typedef boost::shared_ptr< ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetRobotPoseResponse_

typedef ::hiwonder_interfaces::SetRobotPoseResponse_<std::allocator<void> > SetRobotPoseResponse;

typedef boost::shared_ptr< ::hiwonder_interfaces::SetRobotPoseResponse > SetRobotPoseResponsePtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::SetRobotPoseResponse const> SetRobotPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.pulse == rhs.pulse &&
    lhs.current_pulse == rhs.current_pulse &&
    lhs.rpy == rhs.rpy &&
    lhs.min_variation == rhs.min_variation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c52778e84437abb947755843584a67be";
  }

  static const char* value(const ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc52778e84437abb9ULL;
  static const uint64_t static_value2 = 0x47755843584a67beULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/SetRobotPoseResponse";
  }

  static const char* value(const ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"float64[] pulse\n"
"float64[] current_pulse\n"
"float64[] rpy\n"
"float64 min_variation\n"
"\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.pulse);
      stream.next(m.current_pulse);
      stream.next(m.rpy);
      stream.next(m.min_variation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRobotPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::SetRobotPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "pulse[]" << std::endl;
    for (size_t i = 0; i < v.pulse.size(); ++i)
    {
      s << indent << "  pulse[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pulse[i]);
    }
    s << indent << "current_pulse[]" << std::endl;
    for (size_t i = 0; i < v.current_pulse.size(); ++i)
    {
      s << indent << "  current_pulse[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.current_pulse[i]);
    }
    s << indent << "rpy[]" << std::endl;
    for (size_t i = 0; i < v.rpy.size(); ++i)
    {
      s << indent << "  rpy[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.rpy[i]);
    }
    s << indent << "min_variation: ";
    Printer<double>::stream(s, indent + "  ", v.min_variation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SETROBOTPOSERESPONSE_H
