// Generated by gencpp from file hiwonder_interfaces/SetRobotPose.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SETROBOTPOSE_H
#define HIWONDER_INTERFACES_MESSAGE_SETROBOTPOSE_H

#include <ros/service_traits.h>


#include <hiwonder_interfaces/SetRobotPoseRequest.h>
#include <hiwonder_interfaces/SetRobotPoseResponse.h>


namespace hiwonder_interfaces
{

struct SetRobotPose
{

typedef SetRobotPoseRequest Request;
typedef SetRobotPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRobotPose
} // namespace hiwonder_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hiwonder_interfaces::SetRobotPose > {
  static const char* value()
  {
    return "f7572839eb043d212b753d92bfaef663";
  }

  static const char* value(const ::hiwonder_interfaces::SetRobotPose&) { return value(); }
};

template<>
struct DataType< ::hiwonder_interfaces::SetRobotPose > {
  static const char* value()
  {
    return "hiwonder_interfaces/SetRobotPose";
  }

  static const char* value(const ::hiwonder_interfaces::SetRobotPose&) { return value(); }
};


// service_traits::MD5Sum< ::hiwonder_interfaces::SetRobotPoseRequest> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::SetRobotPose >
template<>
struct MD5Sum< ::hiwonder_interfaces::SetRobotPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::SetRobotPose >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetRobotPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::SetRobotPoseRequest> should match
// service_traits::DataType< ::hiwonder_interfaces::SetRobotPose >
template<>
struct DataType< ::hiwonder_interfaces::SetRobotPoseRequest>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::SetRobotPose >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetRobotPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hiwonder_interfaces::SetRobotPoseResponse> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::SetRobotPose >
template<>
struct MD5Sum< ::hiwonder_interfaces::SetRobotPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::SetRobotPose >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetRobotPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::SetRobotPoseResponse> should match
// service_traits::DataType< ::hiwonder_interfaces::SetRobotPose >
template<>
struct DataType< ::hiwonder_interfaces::SetRobotPoseResponse>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::SetRobotPose >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetRobotPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SETROBOTPOSE_H
