// Generated by gencpp from file hiwonder_interfaces/SetRobotPoseRequest.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SETROBOTPOSEREQUEST_H
#define HIWONDER_INTERFACES_MESSAGE_SETROBOTPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct SetRobotPoseRequest_
{
  typedef SetRobotPoseRequest_<ContainerAllocator> Type;

  SetRobotPoseRequest_()
    : position()
    , pitch(0.0)
    , pitch_range()
    , resolution(0.0)  {
    }
  SetRobotPoseRequest_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , pitch(0.0)
    , pitch_range(_alloc)
    , resolution(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _position_type;
  _position_type position;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _pitch_range_type;
  _pitch_range_type pitch_range;

   typedef double _resolution_type;
  _resolution_type resolution;





  typedef boost::shared_ptr< ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetRobotPoseRequest_

typedef ::hiwonder_interfaces::SetRobotPoseRequest_<std::allocator<void> > SetRobotPoseRequest;

typedef boost::shared_ptr< ::hiwonder_interfaces::SetRobotPoseRequest > SetRobotPoseRequestPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::SetRobotPoseRequest const> SetRobotPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.pitch == rhs.pitch &&
    lhs.pitch_range == rhs.pitch_range &&
    lhs.resolution == rhs.resolution;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25a183f489ac68e41350904c1c9f5c0c";
  }

  static const char* value(const ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25a183f489ac68e4ULL;
  static const uint64_t static_value2 = 0x1350904c1c9f5c0cULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/SetRobotPoseRequest";
  }

  static const char* value(const ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] position\n"
"float64 pitch\n"
"float64[] pitch_range \n"
"float64 resolution\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.pitch);
      stream.next(m.pitch_range);
      stream.next(m.resolution);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetRobotPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::SetRobotPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "pitch_range[]" << std::endl;
    for (size_t i = 0; i < v.pitch_range.size(); ++i)
    {
      s << indent << "  pitch_range[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pitch_range[i]);
    }
    s << indent << "resolution: ";
    Printer<double>::stream(s, indent + "  ", v.resolution);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SETROBOTPOSEREQUEST_H
