// Generated by gencpp from file hiwonder_interfaces/SetStringBoolRequest.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SETSTRINGBOOLREQUEST_H
#define HIWONDER_INTERFACES_MESSAGE_SETSTRINGBOOLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct SetStringBoolRequest_
{
  typedef SetStringBoolRequest_<ContainerAllocator> Type;

  SetStringBoolRequest_()
    : data_str()
    , data_bool(false)  {
    }
  SetStringBoolRequest_(const ContainerAllocator& _alloc)
    : data_str(_alloc)
    , data_bool(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_str_type;
  _data_str_type data_str;

   typedef uint8_t _data_bool_type;
  _data_bool_type data_bool;





  typedef boost::shared_ptr< ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetStringBoolRequest_

typedef ::hiwonder_interfaces::SetStringBoolRequest_<std::allocator<void> > SetStringBoolRequest;

typedef boost::shared_ptr< ::hiwonder_interfaces::SetStringBoolRequest > SetStringBoolRequestPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::SetStringBoolRequest const> SetStringBoolRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data_str == rhs.data_str &&
    lhs.data_bool == rhs.data_bool;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec24791a1d2a38c76215df3c0b46ed30";
  }

  static const char* value(const ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec24791a1d2a38c7ULL;
  static const uint64_t static_value2 = 0x6215df3c0b46ed30ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/SetStringBoolRequest";
  }

  static const char* value(const ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string data_str\n"
"bool data_bool\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data_str);
      stream.next(m.data_bool);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetStringBoolRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::SetStringBoolRequest_<ContainerAllocator>& v)
  {
    s << indent << "data_str: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data_str);
    s << indent << "data_bool: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data_bool);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SETSTRINGBOOLREQUEST_H
