// Generated by gencpp from file hiwonder_interfaces/SetStringBool.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SETSTRINGBOOL_H
#define HIWONDER_INTERFACES_MESSAGE_SETSTRINGBOOL_H

#include <ros/service_traits.h>


#include <hiwonder_interfaces/SetStringBoolRequest.h>
#include <hiwonder_interfaces/SetStringBoolResponse.h>


namespace hiwonder_interfaces
{

struct SetStringBool
{

typedef SetStringBoolRequest Request;
typedef SetStringBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetStringBool
} // namespace hiwonder_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hiwonder_interfaces::SetStringBool > {
  static const char* value()
  {
    return "c3a1ce4d99d15a1a0c350abb00d13216";
  }

  static const char* value(const ::hiwonder_interfaces::SetStringBool&) { return value(); }
};

template<>
struct DataType< ::hiwonder_interfaces::SetStringBool > {
  static const char* value()
  {
    return "hiwonder_interfaces/SetStringBool";
  }

  static const char* value(const ::hiwonder_interfaces::SetStringBool&) { return value(); }
};


// service_traits::MD5Sum< ::hiwonder_interfaces::SetStringBoolRequest> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::SetStringBool >
template<>
struct MD5Sum< ::hiwonder_interfaces::SetStringBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::SetStringBool >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetStringBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::SetStringBoolRequest> should match
// service_traits::DataType< ::hiwonder_interfaces::SetStringBool >
template<>
struct DataType< ::hiwonder_interfaces::SetStringBoolRequest>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::SetStringBool >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetStringBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hiwonder_interfaces::SetStringBoolResponse> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::SetStringBool >
template<>
struct MD5Sum< ::hiwonder_interfaces::SetStringBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::SetStringBool >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetStringBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::SetStringBoolResponse> should match
// service_traits::DataType< ::hiwonder_interfaces::SetStringBool >
template<>
struct DataType< ::hiwonder_interfaces::SetStringBoolResponse>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::SetStringBool >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetStringBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SETSTRINGBOOL_H
