// Generated by gencpp from file hiwonder_interfaces/SetTargetRequest.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SETTARGETREQUEST_H
#define HIWONDER_INTERFACES_MESSAGE_SETTARGETREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hiwonder_interfaces
{
template <class ContainerAllocator>
struct SetTargetRequest_
{
  typedef SetTargetRequest_<ContainerAllocator> Type;

  SetTargetRequest_()
    : label()  {
    }
  SetTargetRequest_(const ContainerAllocator& _alloc)
    : label(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _label_type;
  _label_type label;





  typedef boost::shared_ptr< ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetTargetRequest_

typedef ::hiwonder_interfaces::SetTargetRequest_<std::allocator<void> > SetTargetRequest;

typedef boost::shared_ptr< ::hiwonder_interfaces::SetTargetRequest > SetTargetRequestPtr;
typedef boost::shared_ptr< ::hiwonder_interfaces::SetTargetRequest const> SetTargetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.label == rhs.label;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator1> & lhs, const ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hiwonder_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea23f97416b04c6151d2b576c0665ac1";
  }

  static const char* value(const ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea23f97416b04c61ULL;
  static const uint64_t static_value2 = 0x51d2b576c0665ac1ULL;
};

template<class ContainerAllocator>
struct DataType< ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hiwonder_interfaces/SetTargetRequest";
  }

  static const char* value(const ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 颜色标签，如'red', 'green', 'blue'\n"
"# 垃圾类别，如'BananaPeel'\n"
"string label\n"
;
  }

  static const char* value(const ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTargetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hiwonder_interfaces::SetTargetRequest_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.label);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SETTARGETREQUEST_H
