// Generated by gencpp from file hiwonder_interfaces/SetTarget.msg
// DO NOT EDIT!


#ifndef HIWONDER_INTERFACES_MESSAGE_SETTARGET_H
#define HIWONDER_INTERFACES_MESSAGE_SETTARGET_H

#include <ros/service_traits.h>


#include <hiwonder_interfaces/SetTargetRequest.h>
#include <hiwonder_interfaces/SetTargetResponse.h>


namespace hiwonder_interfaces
{

struct SetTarget
{

typedef SetTargetRequest Request;
typedef SetTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTarget
} // namespace hiwonder_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hiwonder_interfaces::SetTarget > {
  static const char* value()
  {
    return "d74f6627fb1a814ad4bd7b097c68231c";
  }

  static const char* value(const ::hiwonder_interfaces::SetTarget&) { return value(); }
};

template<>
struct DataType< ::hiwonder_interfaces::SetTarget > {
  static const char* value()
  {
    return "hiwonder_interfaces/SetTarget";
  }

  static const char* value(const ::hiwonder_interfaces::SetTarget&) { return value(); }
};


// service_traits::MD5Sum< ::hiwonder_interfaces::SetTargetRequest> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::SetTarget >
template<>
struct MD5Sum< ::hiwonder_interfaces::SetTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::SetTarget >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::SetTargetRequest> should match
// service_traits::DataType< ::hiwonder_interfaces::SetTarget >
template<>
struct DataType< ::hiwonder_interfaces::SetTargetRequest>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::SetTarget >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hiwonder_interfaces::SetTargetResponse> should match
// service_traits::MD5Sum< ::hiwonder_interfaces::SetTarget >
template<>
struct MD5Sum< ::hiwonder_interfaces::SetTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hiwonder_interfaces::SetTarget >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hiwonder_interfaces::SetTargetResponse> should match
// service_traits::DataType< ::hiwonder_interfaces::SetTarget >
template<>
struct DataType< ::hiwonder_interfaces::SetTargetResponse>
{
  static const char* value()
  {
    return DataType< ::hiwonder_interfaces::SetTarget >::value();
  }
  static const char* value(const ::hiwonder_interfaces::SetTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIWONDER_INTERFACES_MESSAGE_SETTARGET_H
